In [1]:
import cv2

In [2]:
from numpy import asarray
from numpy import save


In [17]:
import numpy as np
import os
import cv2

IMG_DIR = '/Users/ozgecanyuzer/Documents/Classes/Ling_412/Preprocessing/Cropped Images/train'

for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)
        if img_array is not None:
            img_array = (img_array.flatten())
        img_array  = img_array.reshape(-1, 1).T
        with open('train.csv', 'w') as f:
            np.savetxt(f, img_array, delimiter=",")
        print(img_array)
            
        
        

[[ 70  77  87 ... 106 106 106]]
[[ 67  68  69 ... 106 105 104]]
[[104 117 105 ... 105 104 103]]
[[ 73  79  87 ... 109 109 109]]
[[ 82  83  83 ... 103 103 103]]
[[73 77 83 ... 92 92 92]]
[[93 94 96 ... 98 98 98]]
[[88 91 96 ... 95 95 95]]
[[76 76 76 ... 97 97 97]]
[[98 98 98 ... 87 86 85]]
[[96 97 98 ... 90 90 89]]
[[95 95 95 ... 87 86 86]]
[[64 64 65 ... 98 98 98]]
[[ 64  71  81 ... 103 103 103]]
[[110 110 110 ... 104 104 104]]
[[ 69  75  84 ... 106 106 106]]
[[ 61  62  64 ... 106 105 104]]
[[91 93 96 ... 95 95 95]]
[[88 90 93 ... 93 93 93]]
[[ 69  70  70 ... 106 105 104]]
[[ 71  77  84 ... 118 118 118]]
[[81 85 90 ... 92 92 92]]
[[ 70  75  83 ... 116 116 116]]
[[68 68 67 ... 95 95 95]]
[[ 74  80  88 ... 106 106 106]]
[[ 68  69  70 ... 105 104 103]]
[[106 106 119 ... 103 103 103]]
[[88 91 94 ... 99 99 99]]
[[68 71 75 ... 94 94 94]]
[[53 53 54 ... 82 82 82]]
[[105 107 101 ... 104 103 102]]
[[83 85 89 ... 96 96 96]]
[[ 71  77  84 ... 118 118 118]]
[[65 70 77 ... 99 99 99]]
[[ 71  78  88 

[[70 75 78 ... 97 97 97]]
[[ 73  79  87 ... 107 107 106]]
[[107 104 101 ...  98  98  98]]
[[95 95 95 ... 87 87 87]]
[[112 113 114 ... 101 101 101]]
[[73 73 73 ... 95 95 95]]
[[107 107 107 ...  96  96  96]]
[[94 94 94 ... 85 85 85]]
[[94 95 97 ... 90 90 90]]
[[93 94 95 ... 83 83 83]]
[[78 82 87 ... 87 87 87]]
[[ 95  96  98 ... 100 100 100]]
[[ 97  98 100 ... 103 103 103]]
[[107 107 108 ...  97  97  97]]
[[ 67  68  69 ... 106 105 104]]
[[111 105 111 ... 103 103 103]]
[[63 67 74 ... 95 95 95]]
[[97 97 97 ... 86 85 85]]
[[71 76 78 ... 96 96 96]]
[[106 106 107 ...  95  95  95]]
[[72 74 77 ... 92 92 92]]
[[102 102 103 ...  97  97  97]]
[[108 108 109 ...  94  94  94]]
[[94 95 97 ... 89 89 89]]
[[ 70  75  84 ... 116 116 116]]
[[96 96 97 ... 98 98 98]]
[[ 67  68  69 ... 106 105 104]]
[[109 110 114 ... 105 104 104]]
[[95 95 95 ... 86 86 86]]
[[95 96 97 ... 90 90 90]]
[[77 81 86 ... 89 89 89]]
[[ 67  68  68 ... 102 101 100]]
[[ 70  71  72 ... 109 108 108]]
[[86 88 90 ... 82 82 82]]
[[86 89 92 ...

[[ 84  85  85 ... 106 106 106]]
[[106 115 110 ... 109 109 109]]
[[91 92 94 ... 97 97 97]]
[[93 93 93 ... 84 84 84]]
[[95 95 95 ... 87 86 86]]
[[96 97 99 ... 97 97 97]]
[[ 67  69  70 ... 109 108 107]]
[[112 112 111 ... 108 108 108]]
[[94 96 98 ... 97 97 97]]
[[82 85 89 ... 88 88 88]]
[[95 96 97 ... 91 91 91]]
[[92 93 95 ... 97 97 97]]
[[ 67  74  84 ... 103 103 103]]
[[41 40 39 ... 77 77 77]]
[[91 92 94 ... 84 84 84]]
[[106 106 107 ...  96  96  96]]
[[106 106 107 ...  99  99  99]]
[[38 37 36 ... 77 77 77]]
[[70 75 76 ... 95 95 95]]
[[91 92 94 ... 95 95 95]]
[[ 68  69  69 ... 110 110 109]]
[[79 83 88 ... 91 91 91]]
[[100 100 101 ...  93  93  93]]
[[ 66  67  68 ... 109 108 107]]
[[ 67  68  69 ... 107 106 105]]
[[88 88 89 ... 93 93 93]]
[[92 95 99 ... 95 95 95]]
[[113 116 105 ... 109 109 109]]
[[ 81  82  82 ... 105 105 105]]
[[114 117 105 ... 108 108 108]]
[[96 96 96 ... 87 87 87]]
[[ 68  69  70 ... 109 108 107]]
[[93 94 94 ... 88 88 88]]
[[94 95 97 ... 99 99 99]]
[[81 85 90 ... 94 94 94]]


[[78 82 87 ... 87 87 87]]
[[ 95  96  98 ... 100 100 100]]
[[93 94 95 ... 83 83 83]]
[[94 95 97 ... 90 90 90]]
[[98 98 98 ... 85 85 85]]
[[91 92 94 ... 94 94 94]]
[[124 106 115 ... 108 107 106]]
[[67 70 75 ... 97 97 97]]
[[64 64 65 ... 98 98 98]]
[[ 82  85  90 ... 102 102 102]]
[[78 81 84 ... 94 94 94]]
[[107 108 109 ...  97  97  97]]
[[88 90 92 ... 82 82 82]]
[[ 67  69  71 ... 112 111 110]]
[[65 70 77 ... 98 98 98]]
[[90 91 93 ... 93 93 93]]
[[98 98 98 ... 86 85 84]]
[[111 112 112 ... 103 103 103]]
[[88 88 88 ... 81 81 81]]
[[66 68 73 ... 97 97 97]]
[[ 67  69  71 ... 112 111 110]]
[[ 90  92  95 ... 102 102 102]]
[[65 65 65 ... 95 95 95]]
[[41 40 37 ... 77 77 77]]
[[96 96 96 ... 92 92 92]]
[[73 72 73 ... 97 97 97]]
[[96 97 98 ... 95 95 95]]
[[42 41 39 ... 77 77 77]]
[[108 110 112 ...  97  97  97]]
[[ 70  77  86 ... 105 105 105]]
[[78 82 87 ... 88 87 85]]
[[79 83 88 ... 91 91 91]]
[[ 69  75  84 ... 104 104 104]]
[[65 65 66 ... 99 99 99]]
[[ 86  89  94 ... 107 107 107]]
[[91 92 92 ... 92 

[[91 93 96 ... 95 95 95]]
[[ 61  62  64 ... 106 105 104]]
[[ 69  75  84 ... 106 106 106]]
[[110 110 110 ... 104 104 104]]
[[ 64  71  81 ... 103 103 103]]
[[64 64 65 ... 98 98 98]]
[[95 95 95 ... 87 86 86]]
[[96 97 98 ... 90 90 89]]
[[98 98 98 ... 87 86 85]]
[[76 76 76 ... 97 97 97]]
[[105 107 101 ... 104 103 102]]
[[53 53 54 ... 82 82 82]]
[[ 71  77  84 ... 118 118 118]]
[[83 85 89 ... 96 96 96]]
[[65 70 77 ... 99 99 99]]
[[95 95 95 ... 87 87 87]]
[[ 71  78  88 ... 106 106 106]]
[[ 80  81  81 ... 100 100 100]]
[[79 83 89 ... 92 92 91]]
[[105 112 114 ... 105 105 105]]
[[89 90 92 ... 84 84 84]]
[[ 69  70  70 ... 106 105 104]]
[[ 71  77  84 ... 118 118 118]]
[[81 85 90 ... 92 92 92]]
[[ 70  75  83 ... 116 116 116]]
[[106 106 119 ... 103 103 103]]
[[ 68  69  70 ... 105 104 103]]
[[ 74  80  88 ... 106 106 106]]
[[68 68 67 ... 95 95 95]]
[[68 71 75 ... 94 94 94]]
[[88 91 94 ... 99 99 99]]
[[96 97 98 ... 90 90 89]]
[[76 76 76 ... 97 97 97]]
[[95 95 95 ... 87 86 86]]
[[110 110 110 ... 104 104 

[[ 67  72  80 ... 114 114 114]]
[[ 90  92  95 ... 102 102 102]]
[[ 67  74  85 ... 109 109 109]]
[[66 68 73 ... 97 97 97]]
[[82 85 89 ... 99 99 99]]
[[88 88 88 ... 81 81 81]]
[[98 98 98 ... 86 85 84]]
[[111 112 112 ... 103 103 103]]
[[90 91 93 ... 93 93 93]]
[[55 55 56 ... 82 82 82]]
[[ 68  73  81 ... 113 113 113]]
[[96 96 97 ... 98 98 98]]
[[109 110 114 ... 105 104 104]]
[[ 67  68  69 ... 106 105 104]]
[[95 95 95 ... 86 86 86]]
[[95 96 97 ... 90 90 90]]
[[ 69  76  86 ... 103 103 103]]
[[77 81 86 ... 89 89 89]]
[[ 67  68  68 ... 102 101 100]]
[[63 67 74 ... 95 95 95]]
[[97 97 97 ... 86 85 85]]
[[71 76 78 ... 96 96 96]]
[[70 75 77 ... 95 95 95]]
[[106 106 107 ...  95  95  95]]
[[ 69  75  84 ... 104 104 104]]
[[102 102 103 ...  97  97  97]]
[[72 74 77 ... 92 92 92]]
[[ 70  75  84 ... 116 116 116]]
[[108 108 109 ...  94  94  94]]
[[94 95 97 ... 89 89 89]]
[[43 42 39 ... 78 78 78]]
[[94 95 97 ... 90 90 90]]
[[ 65  66  67 ... 104 103 102]]
[[78 82 87 ... 87 87 87]]
[[ 69  75  83 ... 104 104 

[[81 85 90 ... 94 94 94]]
[[94 95 97 ... 99 99 99]]
[[93 94 94 ... 88 88 88]]
[[ 68  69  70 ... 109 108 107]]
[[ 81  82  82 ... 105 105 105]]
[[96 96 96 ... 87 87 87]]
[[114 117 105 ... 108 108 108]]
[[92 95 99 ... 95 95 95]]
[[88 88 89 ... 93 93 93]]
[[ 67  68  69 ... 107 106 105]]
[[ 66  67  68 ... 109 108 107]]
[[81 85 90 ... 94 94 94]]
[[ 88  91  95 ... 105 105 105]]
[[103 103 104 ...  94  94  94]]
[[ 68  69  70 ... 110 109 108]]
[[94 95 96 ... 95 95 95]]
[[70 74 75 ... 95 95 95]]
[[40 39 38 ... 77 77 77]]
[[40 39 38 ... 76 76 76]]
[[67 68 68 ... 96 96 96]]
[[ 66  67  68 ... 109 108 107]]
[[ 67  68  69 ... 107 106 105]]
[[88 88 89 ... 93 93 93]]
[[92 95 99 ... 95 95 95]]
[[96 96 96 ... 87 87 87]]
[[114 117 105 ... 108 108 108]]
[[ 81  82  82 ... 105 105 105]]
[[ 68  69  70 ... 109 108 107]]
[[93 94 94 ... 88 88 88]]
[[94 95 97 ... 99 99 99]]
[[39 38 35 ... 75 75 75]]
[[92 93 95 ... 97 97 97]]
[[41 40 39 ... 77 77 77]]
[[ 67  74  84 ... 103 103 103]]
[[106 106 107 ...  99  99  99]]


[[ 67  68  69 ... 106 105 104]]
[[109 110 114 ... 105 104 104]]
[[96 96 97 ... 98 98 98]]
[[43 42 39 ... 78 78 78]]
[[94 95 97 ... 89 89 89]]
[[108 108 109 ...  94  94  94]]
[[ 70  75  84 ... 116 116 116]]
[[72 74 77 ... 92 92 92]]
[[102 102 103 ...  97  97  97]]
[[ 69  75  84 ... 104 104 104]]
[[106 106 107 ...  95  95  95]]
[[70 75 77 ... 95 95 95]]
[[71 76 78 ... 96 96 96]]
[[97 97 97 ... 86 85 85]]
[[63 67 74 ... 95 95 95]]
[[88 88 88 ... 81 81 81]]
[[82 85 89 ... 99 99 99]]
[[66 68 73 ... 97 97 97]]
[[ 67  74  85 ... 109 109 109]]
[[ 90  92  95 ... 102 102 102]]
[[ 67  72  80 ... 114 114 114]]
[[97 97 97 ... 85 85 85]]
[[ 68  73  81 ... 113 113 113]]
[[55 55 56 ... 82 82 82]]
[[90 91 93 ... 93 93 93]]
[[111 112 112 ... 103 103 103]]
[[98 98 98 ... 86 85 84]]
[[ 67  72  80 ... 112 112 112]]
[[ 82  85  90 ... 102 102 102]]
[[ 70  76  86 ... 109 109 109]]
[[98 98 98 ... 87 86 86]]
[[88 90 92 ... 82 82 82]]
[[ 82  85  90 ... 102 102 102]]
[[107 108 109 ...  97  97  97]]
[[98 98 98 ...

[[105 107 101 ... 104 103 102]]
[[88 91 94 ... 99 99 99]]
[[68 71 75 ... 94 94 94]]
[[68 68 67 ... 95 95 95]]
[[106 106 119 ... 103 103 103]]
[[ 74  80  88 ... 106 106 106]]
[[ 68  69  70 ... 105 104 103]]
[[ 70  75  83 ... 116 116 116]]
[[81 85 90 ... 92 92 92]]
[[ 71  77  84 ... 118 118 118]]
[[ 69  70  70 ... 106 105 104]]
[[ 67  68  69 ... 106 105 104]]
[[95 95 96 ... 97 97 97]]
[[109 109 110 ... 102 102 102]]
[[ 68  75  85 ... 105 105 105]]
[[100 102 105 ...  96  96  96]]
[[114 120 111 ... 104 104 104]]
[[93 94 96 ... 87 87 87]]
[[ 67  73  82 ... 102 101 100]]
[[ 92  96 101 ... 103 103 103]]
[[ 70  74  81 ... 115 115 115]]
[[40 39 38 ... 76 76 76]]
[[96 97 98 ... 91 91 91]]
[[75 80 85 ... 87 87 87]]
[[94 95 97 ... 99 99 99]]
[[ 70  75  82 ... 115 115 115]]
[[91 92 92 ... 92 92 92]]
[[ 68  75  85 ... 103 103 103]]
[[59 59 58 ... 79 79 79]]
[[94 95 96 ... 95 95 95]]
[[69 70 70 ... 97 96 95]]
[[ 85  88  93 ... 104 104 104]]
[[104 105 106 ...  98  98  98]]
[[52 52 53 ... 81 81 81]]
[[

[[118 115 111 ... 106 106 106]]
[[92 95 99 ... 95 95 95]]
[[79 83 88 ... 91 91 91]]
[[96 96 97 ... 99 99 99]]
[[94 94 94 ... 84 83 82]]
[[68 68 68 ... 94 94 94]]
[[94 95 97 ... 87 87 87]]
[[112 104 112 ... 109 109 109]]
[[92 94 95 ... 90 90 90]]
[[93 94 96 ... 95 95 95]]
[[97 98 99 ... 90 90 90]]
[[ 83  83  83 ... 103 103 103]]
[[79 83 89 ... 92 92 91]]
[[73 77 83 ... 90 90 90]]
[[70 75 77 ... 95 95 95]]
[[109 111 112 ... 104 104 104]]
[[85 89 94 ... 97 97 97]]
[[106 118 110 ... 106 106 106]]
[[73 78 84 ... 86 85 84]]
[[85 85 85 ... 76 75 74]]
[[93 94 96 ... 97 97 97]]
[[76 83 90 ... 94 94 94]]
[[87 87 87 ... 76 75 74]]
[[94 94 95 ... 84 84 84]]
[[111 112 112 ... 103 103 103]]
[[89 90 90 ... 89 89 89]]
[[ 93  96 100 ...  97  97  97]]
[[71 72 73 ... 97 97 97]]
[[78 83 89 ... 93 93 93]]
[[ 67  68  69 ... 106 105 104]]
[[ 72  78  86 ... 105 105 105]]
[[81 84 88 ... 95 95 95]]
[[110 110 111 ...  96  96  96]]
[[88 89 89 ... 83 83 83]]
[[ 82  82  82 ... 103 103 103]]
[[ 72  77  84 ... 103 10

[[104 104 105 ...  95  95  95]]
[[84 85 87 ... 89 89 89]]
[[ 67  68  69 ... 103 102 101]]
[[ 70  72  73 ... 112 111 110]]
[[96 96 96 ... 85 85 85]]
[[ 70  77  87 ... 109 109 109]]
[[109 118 105 ... 106 106 105]]
[[ 93  96 101 ...  99  99  99]]
[[40 38 36 ... 77 77 77]]
[[ 67  68  69 ... 107 106 105]]
[[60 64 69 ... 91 91 91]]
[[94 94 95 ... 81 81 81]]
[[95 95 95 ... 85 84 83]]
[[92 92 92 ... 82 82 82]]
[[64 64 65 ... 97 97 97]]
[[ 96  97  99 ... 103 103 103]]
[[ 80  81  81 ... 101 101 101]]
[[ 73  79  87 ... 109 109 109]]
[[ 71  72  72 ... 101 100  99]]
[[111 115 113 ... 104 103 102]]
[[ 70  77  87 ... 109 109 109]]
[[96 96 96 ... 85 85 85]]
[[ 70  72  73 ... 112 111 110]]
[[ 67  68  69 ... 103 102 101]]
[[84 85 87 ... 89 89 89]]
[[104 104 105 ...  95  95  95]]
[[ 70  76  84 ... 103 103 103]]
[[ 65  68  73 ... 101 100  99]]
[[63 64 65 ... 95 94 94]]
[[ 71  72  72 ... 101 100  99]]
[[ 73  79  87 ... 109 109 109]]
[[111 115 113 ... 104 103 102]]
[[ 80  81  81 ... 101 101 101]]
[[ 96  97 

[[ 73  79  87 ... 107 107 106]]
[[96 96 96 ... 84 83 82]]
[[ 82  82  82 ... 103 103 103]]
[[88 89 89 ... 83 83 83]]
[[110 110 111 ...  96  96  96]]
[[81 84 88 ... 95 95 95]]
[[ 72  78  86 ... 105 105 105]]
[[71 72 73 ... 97 97 97]]
[[ 67  68  69 ... 106 105 104]]
[[78 83 89 ... 93 93 93]]
[[ 93  96 100 ...  97  97  97]]
[[38 38 38 ... 78 78 78]]
[[61 61 61 ... 90 90 90]]
[[ 85  84  83 ... 110 110 110]]
[[ 70  77  87 ... 105 105 105]]
[[60 62 62 ... 94 93 93]]
[[ 63  67  73 ... 102 102 102]]
[[114 115 115 ... 100 100 100]]
[[ 86  89  94 ... 107 107 107]]
[[67 73 78 ... 93 93 93]]
[[ 70  71  71 ... 106 105 105]]
[[ 72  77  85 ... 104 104 104]]
[[ 72  77  84 ... 103 103 103]]
[[97 97 97 ... 86 86 86]]
[[109 111 112 ... 104 104 104]]
[[70 75 77 ... 95 95 95]]
[[73 77 83 ... 90 90 90]]
[[79 83 89 ... 92 92 91]]
[[ 83  83  83 ... 103 103 103]]
[[97 98 99 ... 90 90 90]]
[[93 94 96 ... 95 95 95]]
[[92 94 95 ... 90 90 90]]
[[94 95 97 ... 87 87 87]]
[[68 68 68 ... 94 94 94]]
[[112 104 112 ... 10

[[ 65  72  82 ... 103 103 103]]
[[86 88 92 ... 97 97 97]]
[[ 67  71  78 ... 110 110 110]]
[[ 99 101 103 ...  96  96  96]]
[[106 104 115 ... 104 104 104]]
[[96 96 96 ... 89 89 89]]
[[39 38 36 ... 74 74 74]]
[[92 93 93 ... 87 87 87]]
[[95 96 97 ... 98 98 98]]
[[ 96  98 101 ...  92  92  92]]
[[ 65  66  67 ... 103 102 102]]
[[92 92 92 ... 79 78 77]]
[[ 68  75  85 ... 105 105 105]]
[[109 109 110 ... 102 102 102]]
[[95 95 96 ... 97 97 97]]
[[ 67  68  69 ... 106 105 104]]
[[94 95 97 ... 99 99 99]]
[[96 97 98 ... 91 91 91]]
[[75 80 85 ... 87 87 87]]
[[ 92  96 101 ... 103 103 103]]
[[40 39 38 ... 76 76 76]]
[[ 70  74  81 ... 115 115 115]]
[[ 67  73  82 ... 102 101 100]]
[[93 94 96 ... 87 87 87]]
[[114 120 111 ... 104 104 104]]
[[100 102 105 ...  96  96  96]]
[[92 92 92 ... 79 78 77]]
[[ 65  66  67 ... 103 102 102]]
[[95 96 97 ... 98 98 98]]
[[ 78  78  78 ... 104 104 104]]
[[39 38 36 ... 74 74 74]]
[[106 104 115 ... 104 104 104]]
[[ 67  71  78 ... 110 110 110]]
[[86 88 92 ... 97 97 97]]
[[ 65  7

[[85 85 85 ... 76 75 74]]
[[111 112 112 ... 103 103 103]]
[[ 68  69  70 ... 102 101 100]]
[[89 90 90 ... 89 89 89]]
[[92 94 95 ... 90 90 90]]
[[112 104 112 ... 109 109 109]]
[[68 68 68 ... 94 94 94]]
[[93 94 96 ... 95 95 95]]
[[ 83  83  83 ... 103 103 103]]
[[97 98 99 ... 90 90 90]]
[[79 83 89 ... 92 92 91]]
[[109 111 112 ... 104 104 104]]
[[70 75 77 ... 95 95 95]]
[[99 99 99 ... 91 91 91]]
[[88 88 89 ... 76 76 76]]
[[91 91 91 ... 81 81 80]]
[[91 92 92 ... 92 92 92]]
[[105 106 107 ... 101 101 101]]
[[ 99 100 101 ...  95  95  95]]
[[ 64  65  66 ... 102 101 101]]
[[37 36 36 ... 77 77 77]]
[[ 66  67  68 ... 103 102 102]]
[[ 68  73  82 ... 114 114 114]]
[[79 83 88 ... 91 91 91]]
[[96 96 97 ... 99 99 99]]
[[94 94 94 ... 84 83 82]]
[[92 95 99 ... 95 95 95]]
[[ 65  65  65 ... 103 102 102]]
[[78 82 87 ... 88 87 85]]
[[103 104 105 ...  98  98  98]]
[[108 110 112 ...  97  97  97]]
[[96 97 98 ... 95 95 95]]
[[55 56 56 ... 82 82 82]]
[[73 72 73 ... 97 97 97]]
[[38 37 36 ... 77 77 77]]
[[96 96 96 .

[[82 85 89 ... 88 88 88]]
[[94 96 98 ... 97 97 97]]
[[ 67  69  70 ... 109 108 107]]
[[91 92 94 ... 97 97 97]]
[[93 93 93 ... 84 84 84]]
[[ 66  68  69 ... 107 106 105]]
[[106 115 110 ... 109 109 109]]
[[94 94 95 ... 88 88 88]]
[[88 88 89 ... 77 77 77]]
[[ 84  85  85 ... 106 106 106]]
[[40 38 36 ... 77 77 77]]
[[ 93  96 101 ...  99  99  99]]
[[109 118 105 ... 106 106 105]]
[[94 94 95 ... 81 81 81]]
[[60 64 69 ... 91 91 91]]
[[ 67  68  69 ... 107 106 105]]
[[94 94 94 ... 84 84 84]]
[[95 95 95 ... 85 84 83]]
[[64 64 65 ... 97 97 97]]
[[92 92 92 ... 82 82 82]]
[[ 96  97  99 ... 103 103 103]]
[[ 80  81  81 ... 101 101 101]]
[[74 79 85 ... 90 90 90]]
[[111 115 113 ... 104 103 102]]
[[ 71  72  72 ... 101 100  99]]
[[ 73  79  87 ... 109 109 109]]
[[63 64 65 ... 95 94 94]]
[[104 104 105 ...  95  95  95]]
[[ 65  68  73 ... 101 100  99]]
[[84 85 87 ... 89 89 89]]
[[ 67  68  69 ... 103 102 101]]
[[ 70  72  73 ... 112 111 110]]
[[ 68  76  86 ... 102 102 102]]
[[96 96 96 ... 85 85 85]]
[[ 70  77  87 

[[102 102 103 ...  97  97  97]]
[[72 74 77 ... 92 92 92]]
[[94 95 96 ... 95 95 95]]
[[106 106 107 ...  95  95  95]]
[[71 76 78 ... 96 96 96]]
[[ 85  88  93 ... 104 104 104]]
[[87 87 88 ... 92 92 92]]
[[96 97 98 ... 95 95 95]]
[[111 105 111 ... 103 103 103]]
[[ 67  68  69 ... 106 105 104]]
[[64 67 72 ... 95 95 95]]
[[ 68  68  68 ... 101 100  99]]
[[ 97  98 100 ... 103 103 103]]
[[95 96 97 ... 94 94 94]]
[[78 82 87 ... 87 87 87]]
[[94 95 97 ... 90 90 90]]
[[96 96 96 ... 90 90 90]]
[[ 70  77  87 ... 106 106 106]]
[[77 82 88 ... 94 94 94]]
[[94 94 94 ... 85 85 85]]
[[73 73 73 ... 95 95 95]]
[[ 86  89  94 ... 106 106 106]]
[[112 113 114 ... 101 101 101]]
[[95 95 95 ... 87 87 87]]
[[91 91 91 ... 82 82 82]]
[[107 104 101 ...  98  98  98]]
[[70 75 78 ... 97 97 97]]
[[36 36 34 ... 75 75 75]]
[[ 70  77  87 ... 105 105 105]]
[[ 85  84  83 ... 110 110 110]]
[[ 75  82  92 ... 111 111 111]]
[[61 61 61 ... 90 90 90]]
[[ 63  67  73 ... 102 102 102]]
[[ 84  87  92 ... 105 105 105]]
[[114 115 115 ... 10

[[97 97 98 ... 97 96 96]]
[[ 72  79  88 ... 106 106 106]]
[[ 69  76  85 ... 103 103 103]]
[[81 84 88 ... 95 95 95]]
[[106 106 107 ...  92  92  92]]
[[87 87 87 ... 75 74 73]]
[[94 95 96 ... 89 89 89]]
[[79 84 90 ... 96 96 96]]
[[69 69 70 ... 97 97 97]]
[[113 114 114 ... 104 104 104]]
[[89 90 92 ... 84 84 84]]
[[ 80  81  81 ... 100 100 100]]
[[65 70 77 ... 99 99 99]]
[[ 71  78  88 ... 106 106 106]]
[[ 65  72  82 ... 108 108 108]]
[[105 107 101 ... 104 103 102]]
[[53 53 54 ... 82 82 82]]
[[71 73 75 ... 96 96 96]]
[[ 71  77  84 ... 118 118 118]]
[[83 85 89 ... 96 96 96]]
[[39 38 36 ... 74 74 74]]
[[72 77 81 ... 98 98 98]]
[[109 110 112 ... 104 104 104]]
[[88 91 94 ... 99 99 99]]
[[ 70  75  83 ... 116 116 116]]
[[95 97 99 ... 89 89 89]]
[[106 106 119 ... 103 103 103]]
[[ 68  69  70 ... 105 104 103]]
[[ 74  80  88 ... 106 106 106]]
[[ 69  70  70 ... 106 105 104]]
[[67 66 65 ... 84 84 84]]
[[ 69  75  84 ... 106 106 106]]
[[ 72  78  87 ... 108 108 108]]
[[ 68  73  80 ... 114 114 114]]
[[110 11

[[65 65 66 ... 99 99 99]]
[[77 81 87 ... 94 94 94]]
[[112 113 113 ... 108 108 108]]
[[68 71 75 ... 95 95 95]]
[[85 88 91 ... 96 96 96]]
[[95 95 95 ... 80 80 80]]
[[96 96 96 ... 89 89 89]]
[[96 95 95 ... 87 87 87]]
[[110 110 111 ... 105 105 105]]
[[98 98 99 ... 94 94 94]]
[[ 99  99 100 ...  95  95  95]]
[[81 85 90 ... 91 91 91]]
[[ 69  73  80 ... 114 114 114]]
[[ 70  71  73 ... 108 107 106]]
[[70 71 71 ... 97 97 97]]
[[93 95 98 ... 88 87 87]]
[[ 78  78  78 ... 104 104 104]]
[[42 41 38 ... 77 77 77]]
[[89 90 92 ... 84 84 84]]
[[95 95 95 ... 86 86 86]]
[[86 88 93 ... 98 98 98]]
[[93 94 94 ... 88 88 88]]
[[74 79 85 ... 90 90 90]]
[[66 66 66 ... 97 97 97]]
[[90 90 90 ... 78 78 78]]
[[93 94 95 ... 96 96 96]]
[[65 65 64 ... 99 98 97]]
[[73 80 88 ... 92 92 92]]
[[102 105 109 ... 100 100 100]]
[[94 96 98 ... 89 89 89]]
[[ 69  75  84 ... 104 104 104]]
[[53 55 56 ... 85 84 83]]
[[41 40 38 ... 78 78 78]]
[[96 96 97 ... 95 95 95]]
[[73 78 84 ... 86 85 84]]
[[110 110 111 ... 103 103 103]]
[[ 68  75 

[[111 112 112 ... 104 104 104]]
[[66 69 73 ... 97 97 97]]
[[82 82 83 ... 72 72 72]]
[[38 37 35 ... 73 73 73]]
[[74 78 80 ... 96 96 96]]
[[95 95 95 ... 84 83 82]]
[[95 96 96 ... 91 91 91]]
[[76 82 88 ... 94 94 94]]
[[85 87 91 ... 97 97 97]]
[[72 77 85 ... 86 85 85]]
[[117 104 115 ... 109 109 109]]
[[95 95 95 ... 82 82 82]]
[[ 82  83  83 ... 104 104 104]]
[[108 109 110 ... 104 104 104]]
[[53 53 54 ... 82 82 82]]
[[82 86 91 ... 91 90 89]]
[[104 105 106 ... 102 102 102]]
[[ 69  74  81 ... 114 114 114]]
[[69 77 85 ... 86 86 86]]
[[75 81 88 ... 93 92 92]]
[[96 96 97 ... 82 82 82]]
[[78 83 88 ... 88 88 88]]
[[ 68  73  80 ... 114 114 114]]
[[82 85 89 ... 99 99 99]]
[[85 86 88 ... 77 77 77]]
[[63 64 64 ... 84 84 84]]
[[94 94 94 ... 84 83 82]]
[[73 77 82 ... 86 86 86]]
[[ 99  99 100 ...  95  95  95]]
[[73 76 79 ... 91 91 91]]
[[81 85 90 ... 94 94 94]]
[[113 113 114 ...  99  99  99]]
[[ 65  66  67 ... 105 104 103]]
[[82 83 84 ... 77 77 77]]
[[96 96 97 ... 95 95 95]]
[[ 95  97 100 ...  89  89  89]

[[91 91 91 ... 82 82 82]]
[[ 66  71  79 ... 111 111 111]]
[[ 70  75  81 ... 110 110 110]]
[[89 92 96 ... 95 95 95]]
[[88 89 91 ... 93 93 93]]
[[ 82  83  83 ... 104 104 104]]
[[61 62 63 ... 94 93 93]]
[[ 95  97 100 ...  89  89  89]]
[[86 86 87 ... 80 80 80]]
[[61 62 63 ... 91 90 89]]
[[95 96 97 ... 95 95 95]]
[[ 73  79  87 ... 106 106 106]]
[[65 68 72 ... 95 95 95]]
[[ 84  87  92 ... 105 105 105]]
[[ 70  71  72 ... 109 108 108]]
[[ 96  97  99 ... 103 103 103]]
[[94 95 97 ... 95 95 95]]
[[83 84 86 ... 76 76 76]]
[[93 93 93 ... 82 81 80]]
[[ 68  74  83 ... 103 102 102]]
[[90 90 90 ... 78 77 76]]
[[70 70 70 ... 95 95 95]]
[[44 42 40 ... 77 77 77]]
[[76 82 90 ... 96 96 96]]
[[107 107 108 ... 101 101 101]]
[[96 96 97 ... 82 82 82]]
[[74 80 90 ... 95 94 94]]
[[ 69  70  71 ... 107 106 105]]
[[97 97 97 ... 89 89 89]]
[[66 66 66 ... 99 98 97]]
[[ 98  99 100 ... 103 103 103]]
[[45 43 40 ... 77 77 77]]
[[76 80 85 ... 86 86 86]]
[[92 92 92 ... 79 78 77]]
[[95 95 96 ... 90 90 90]]
[[64 65 66 ... 98 

[[93 94 96 ... 97 97 97]]
[[85 86 88 ... 79 79 79]]
[[104 105 106 ...  98  98  98]]
[[92 92 92 ... 82 82 82]]
[[107 108 110 ...  99  99  99]]
[[93 94 96 ... 90 90 90]]
[[101 103 105 ...  97  97  97]]
[[92 93 94 ... 96 96 96]]
[[95 95 96 ... 86 86 85]]
[[68 71 75 ... 94 94 94]]
[[ 77  77  77 ... 103 103 103]]
[[90 93 97 ... 95 95 95]]
[[96 96 97 ... 84 84 84]]
[[105 107 101 ... 104 103 102]]
[[56 56 57 ... 84 84 84]]
[[90 90 90 ... 78 78 78]]
[[112 112 113 ... 106 106 106]]
[[112 112 113 ...  98  98  98]]
[[ 66  67  68 ... 104 103 102]]
[[110 110 111 ... 105 105 105]]
[[59 60 61 ... 95 94 94]]
[[65 68 72 ... 94 94 94]]
[[ 69  76  87 ... 110 110 110]]
[[96 96 96 ... 84 83 82]]
[[95 95 95 ... 83 83 83]]
[[115 114 113 ... 110 110 110]]
[[65 67 72 ... 96 96 96]]
[[69 69 70 ... 97 97 97]]
[[ 99  99 100 ...  94  94  94]]
[[84 85 87 ... 78 78 78]]
[[58 58 59 ... 92 92 92]]
[[79 83 89 ... 93 93 93]]
[[94 95 95 ... 90 90 90]]
[[94 95 96 ... 95 95 95]]
[[67 66 65 ... 87 87 87]]
[[114 113 112 ... 

[[40 38 36 ... 75 75 75]]
[[95 95 95 ... 80 80 80]]
[[60 60 59 ... 91 91 91]]
[[104 104 105 ...  95  95  95]]
[[114 115 115 ... 108 108 108]]
[[58 58 59 ... 88 88 88]]
[[76 80 85 ... 86 86 86]]
[[ 66  67  68 ... 102 101 100]]
[[57 57 57 ... 82 82 82]]
[[96 96 97 ... 86 86 86]]
[[61 63 64 ... 99 98 97]]
[[ 82  83  83 ... 104 104 104]]
[[70 70 70 ... 95 95 95]]
[[ 86  89  94 ... 105 105 105]]
[[105 106 108 ...  97  97  97]]
[[ 71  75  81 ... 113 113 113]]
[[ 71  76  83 ... 117 117 117]]
[[106 108 110 ...  99  98  97]]
[[76 82 90 ... 96 96 96]]
[[44 42 40 ... 77 77 77]]
[[90 90 90 ... 78 77 76]]
[[ 98  99 100 ...  90  89  89]]
[[93 93 93 ... 82 81 80]]
[[ 68  74  83 ... 103 102 102]]
[[76 81 88 ... 93 92 91]]
[[98 98 99 ... 96 96 96]]
[[94 95 97 ... 95 95 95]]
[[ 96  97  99 ... 103 103 103]]
[[ 84  87  92 ... 105 105 105]]
[[ 70  71  72 ... 109 108 108]]
[[105 107 108 ... 101 101 101]]
[[74 79 85 ... 91 91 91]]
[[77 81 87 ... 94 94 94]]
[[38 39 39 ... 76 76 76]]
[[64 65 66 ... 98 97 96]]


[[81 85 90 ... 91 91 91]]
[[112 112 114 ... 104 104 104]]
[[70 74 75 ... 95 95 95]]
[[88 88 88 ... 76 75 74]]
[[41 39 37 ... 73 73 73]]
[[ 96  97  98 ... 100 100 100]]
[[87 90 94 ... 96 96 96]]
[[78 82 88 ... 94 94 94]]
[[ 97  98 100 ... 103 103 103]]
[[73 77 82 ... 86 86 86]]
[[94 94 94 ... 84 83 82]]
[[73 76 79 ... 91 91 91]]
[[ 99  99 100 ...  95  95  95]]
[[81 85 90 ... 94 94 94]]
[[113 113 114 ...  99  99  99]]
[[ 65  66  67 ... 105 104 103]]
[[59 60 60 ... 87 87 87]]
[[ 95  97 100 ...  89  89  89]]
[[96 96 97 ... 95 95 95]]
[[82 83 84 ... 77 77 77]]
[[89 89 89 ... 76 76 76]]
[[ 76  76  76 ... 104 104 104]]
[[78 82 88 ... 94 94 94]]
[[ 97  98 100 ... 103 103 103]]
[[87 90 94 ... 96 96 96]]
[[ 96  97  98 ... 100 100 100]]
[[41 39 37 ... 73 73 73]]
[[88 88 88 ... 76 75 74]]
[[70 74 75 ... 95 95 95]]
[[112 112 114 ... 104 104 104]]
[[ 76  76  76 ... 104 104 104]]
[[89 89 89 ... 76 76 76]]
[[82 83 84 ... 77 77 77]]
[[96 96 97 ... 95 95 95]]
[[ 95  97 100 ...  89  89  89]]
[[59 60 60 .

[[96 96 97 ... 82 82 82]]
[[ 69  70  71 ... 107 106 105]]
[[74 80 90 ... 95 94 94]]
[[97 97 97 ... 89 89 89]]
[[ 98  99 100 ... 103 103 103]]
[[66 66 66 ... 99 98 97]]
[[98 98 99 ... 96 96 96]]
[[76 81 88 ... 93 92 91]]
[[ 68  74  83 ... 103 102 102]]
[[93 93 93 ... 82 81 80]]
[[ 98  99 100 ...  90  89  89]]
[[90 90 90 ... 78 77 76]]
[[76 82 90 ... 96 96 96]]
[[44 42 40 ... 77 77 77]]
[[ 70  71  72 ... 109 108 108]]
[[ 84  87  92 ... 105 105 105]]
[[ 96  97  99 ... 103 103 103]]
[[94 95 97 ... 95 95 95]]
[[61 63 64 ... 99 98 97]]
[[ 82  83  83 ... 104 104 104]]
[[96 96 97 ... 86 86 86]]
[[ 66  67  68 ... 102 101 100]]
[[57 57 57 ... 82 82 82]]
[[76 80 85 ... 86 86 86]]
[[104 104 105 ...  95  95  95]]
[[58 58 59 ... 88 88 88]]
[[114 115 115 ... 108 108 108]]
[[60 60 59 ... 91 91 91]]
[[95 95 95 ... 80 80 80]]
[[40 38 36 ... 75 75 75]]
[[107 112 112 ... 106 106 106]]
[[94 94 95 ... 83 83 83]]
[[60 60 61 ... 94 94 94]]
[[106 108 110 ...  99  98  97]]
[[ 71  75  81 ... 113 113 113]]
[[ 71 

[[ 76  76  76 ... 100 100 100]]
[[103 103 104 ...  97  97  97]]
[[77 81 86 ... 89 89 89]]
[[71 71 71 ... 97 97 97]]
[[103 103 104 ...  97  97  97]]
[[ 68  69  70 ... 102 101 100]]
[[112 112 113 ... 106 106 106]]
[[67 67 67 ... 97 97 97]]
[[95 95 96 ... 91 91 91]]
[[100 100 100 ...  91  91  91]]
[[92 92 92 ... 80 80 79]]
[[85 87 91 ... 97 97 97]]
[[76 81 87 ... 96 95 95]]
[[97 97 97 ... 85 85 85]]
[[109 110 110 ... 103 103 103]]
[[89 89 89 ... 76 76 76]]
[[41 39 37 ... 76 76 76]]
[[95 96 96 ... 91 91 91]]
[[94 95 96 ... 89 89 89]]
[[ 78  78  78 ... 102 102 102]]
[[95 96 97 ... 91 91 91]]
[[95 95 96 ... 88 88 88]]
[[88 88 88 ... 78 78 78]]
[[95 96 97 ... 96 96 96]]
[[40 39 38 ... 76 76 76]]
[[111 111 112 ... 107 107 107]]
[[89 89 90 ... 78 77 76]]
[[109 111 112 ... 104 104 104]]
[[65 69 75 ... 94 94 94]]
[[107 108 109 ...  97  97  97]]
[[95 95 96 ... 90 90 90]]
[[98 98 98 ... 89 89 89]]
[[102 102 103 ...  94  94  94]]
[[91 91 91 ... 80 79 78]]
[[ 74  80  88 ... 106 106 106]]
[[108 108 10

[[99 98 97 ... 91 91 91]]
[[107 107 108 ...  99  99  99]]
[[60 60 60 ... 94 93 93]]
[[ 67  68  68 ... 102 101 100]]
[[ 70  76  83 ... 113 113 113]]
[[81 83 87 ... 95 95 95]]
[[ 86  89  94 ... 105 105 105]]
[[110 114 116 ... 105 105 105]]
[[91 91 91 ... 82 82 82]]
[[59 60 62 ... 97 96 95]]
[[ 80  81  81 ... 100 100 100]]
[[70 75 77 ... 91 91 91]]
[[90 90 91 ... 89 89 89]]
[[63 66 71 ... 95 95 94]]
[[70 72 74 ... 97 97 97]]
[[61 61 62 ... 96 96 96]]
[[102 102 103 ...  94  94  94]]
[[59 59 60 ... 89 89 89]]
[[ 70  75  81 ... 110 110 110]]
[[ 66  71  79 ... 111 111 111]]
[[98 98 98 ... 95 95 95]]
[[65 68 72 ... 95 95 95]]
[[117  97 106 ... 107 106 106]]
[[86 86 87 ... 80 80 80]]
[[108 110 112 ... 108 108 108]]
[[ 82  83  83 ... 104 104 104]]
[[ 84  87  92 ... 105 105 105]]
[[61 62 63 ... 94 93 93]]
[[111 111 111 ... 106 106 106]]
[[74 79 87 ... 87 87 87]]
[[ 96  97  99 ... 103 103 103]]
[[104 105 106 ...  99  99  99]]
[[ 70  71  72 ... 109 108 108]]
[[44 42 40 ... 77 77 77]]
[[78 82 88 ...

[[82 86 91 ... 91 90 89]]
[[69 77 85 ... 86 86 86]]
[[58 58 59 ... 85 85 85]]
[[ 64  65  66 ... 102 101 100]]
[[108 109 110 ... 104 104 104]]
[[ 64  66  67 ... 100  99  99]]
[[78 82 88 ... 94 94 94]]
[[ 69  75  84 ... 104 104 104]]
[[95 95 95 ... 82 82 82]]
[[89 90 92 ... 95 95 95]]
[[63 64 64 ... 84 84 84]]
[[85 86 88 ... 77 77 77]]
[[ 68  74  82 ... 114 114 114]]
[[78 83 88 ... 88 88 88]]
[[ 68  73  80 ... 114 114 114]]
[[75 81 88 ... 93 92 92]]
[[96 96 97 ... 82 82 82]]
[[89 89 89 ... 76 76 76]]
[[ 82  83  83 ... 103 103 103]]
[[100 100 101 ...  93  93  93]]
[[ 76  76  76 ... 104 104 104]]
[[64 67 72 ... 99 99 99]]
[[ 95  97 100 ...  89  89  89]]
[[81 85 90 ... 94 94 94]]
[[113 113 114 ...  99  99  99]]
[[94 94 94 ... 84 83 82]]
[[73 77 82 ... 86 86 86]]
[[ 99  99 100 ...  95  95  95]]
[[73 76 79 ... 91 91 91]]
[[78 82 88 ... 94 94 94]]
[[60 60 61 ... 91 91 91]]
[[41 39 37 ... 73 73 73]]
[[88 88 88 ... 76 75 74]]
[[68 67 66 ... 87 87 87]]
[[75 75 74 ... 99 99 99]]
[[74 81 87 ... 94 

[[ 71  75  81 ... 113 113 113]]
[[ 71  76  83 ... 117 117 117]]
[[105 106 108 ...  97  97  97]]
[[85 89 94 ... 97 97 97]]
[[96 96 97 ... 86 86 86]]
[[65 67 72 ... 91 91 91]]
[[100 100 101 ...  87  87  87]]
[[ 67  68  68 ... 103 102 101]]
[[76 80 85 ... 86 86 86]]
[[39 38 38 ... 77 77 77]]
[[113 109 105 ... 105 105 105]]
[[58 58 59 ... 88 88 88]]
[[114 115 115 ... 108 108 108]]
[[60 60 59 ... 91 91 91]]
[[60 60 61 ... 94 94 94]]
[[66 70 76 ... 96 96 96]]
[[107 112 112 ... 106 106 106]]
[[102 103 104 ...  94  94  94]]
[[68 67 66 ... 87 87 87]]
[[ 78  79  79 ... 104 104 104]]
[[106 107 108 ...  98  98  98]]
[[59 59 58 ... 79 79 79]]
[[65 65 65 ... 95 95 95]]
[[ 70  74  80 ... 114 114 114]]
[[ 67  73  80 ... 111 110 109]]
[[55 55 56 ... 85 85 85]]
[[108 108 109 ...  94  94  94]]
[[69 71 75 ... 98 97 96]]
[[115 106 108 ... 106 106 106]]
[[97 97 97 ... 86 86 86]]
[[70 73 77 ... 96 96 96]]
[[77 81 87 ... 88 87 87]]
[[118 118 118 ... 109 109 109]]
[[53 53 54 ... 82 82 82]]
[[60 60 60 ... 94 93

[[103 103 104 ...  97  97  97]]
[[ 68  69  70 ... 102 101 100]]
[[67 66 65 ... 87 87 87]]
[[90 92 94 ... 84 84 84]]
[[114 113 112 ... 107 107 107]]
[[84 85 87 ... 78 78 78]]
[[94 95 96 ... 95 95 95]]
[[69 69 70 ... 97 97 97]]
[[65 67 72 ... 96 96 96]]
[[95 95 95 ... 83 83 83]]
[[95 95 95 ... 83 83 83]]
[[115 114 113 ... 110 110 110]]
[[110 110 111 ... 105 105 105]]
[[62 62 63 ... 95 95 95]]
[[96 96 96 ... 84 83 82]]
[[65 68 72 ... 94 94 94]]
[[110 120  98 ... 109 109 109]]
[[59 60 61 ... 95 94 94]]
[[112 112 113 ... 106 106 106]]
[[66 66 66 ... 99 98 97]]
[[39 38 36 ... 76 76 76]]
[[96 96 97 ... 84 84 84]]
[[ 65  70  76 ... 107 107 107]]
[[ 77  77  77 ... 103 103 103]]
[[68 71 75 ... 94 94 94]]
[[107 108 110 ...  99  99  99]]
[[62 62 63 ... 95 95 95]]
[[93 94 96 ... 90 90 90]]
[[71 71 72 ... 98 98 98]]
[[ 70  76  84 ... 103 103 103]]
[[78 81 84 ... 94 94 94]]
[[93 94 96 ... 97 97 97]]
[[85 86 88 ... 79 79 79]]
[[99 99 99 ... 90 90 90]]
[[95 95 95 ... 84 84 84]]
[[ 67  68  69 ... 106 10

[[89 90 90 ... 89 89 89]]
[[60 59 58 ... 82 82 82]]
[[78 82 88 ... 87 87 87]]
[[76 82 90 ... 96 96 96]]
[[44 42 40 ... 77 77 77]]
[[90 90 90 ... 78 77 76]]
[[39 38 35 ... 75 75 75]]
[[111 111 111 ... 106 106 106]]
[[74 74 73 ... 97 97 97]]
[[ 96  97  99 ... 103 103 103]]
[[ 70  71  72 ... 109 108 108]]
[[ 85  89  94 ... 101 101 101]]
[[ 83  84  84 ... 104 104 104]]
[[87 90 94 ... 96 96 96]]
[[ 73  80  89 ... 109 109 109]]
[[ 80  81  81 ... 100 100 100]]
[[89 89 90 ... 79 78 77]]
[[ 66  67  68 ... 102 101 100]]
[[92 92 92 ... 84 84 84]]
[[86 89 94 ... 95 95 95]]
[[ 97  98  99 ... 101 101 101]]
[[79 83 89 ... 94 94 94]]
[[ 68  70  71 ... 110 109 108]]
[[94 95 97 ... 89 89 89]]
[[37 37 36 ... 74 74 74]]
[[ 67  68  68 ... 103 102 101]]
[[55 55 56 ... 85 84 83]]
[[91 91 92 ... 93 93 93]]
[[ 66  67  68 ... 101 100  99]]
[[ 81  82  82 ... 101 101 101]]
[[ 95  98 101 ... 100 100 100]]
[[ 97  97  98 ... 100 100 100]]
[[103 103 104 ...  97  97  97]]
[[74 76 79 ... 88 88 88]]
[[89 90 90 ... 84 84

[[97 97 97 ... 85 85 85]]
[[78 82 88 ... 94 94 94]]
[[60 60 61 ... 91 91 91]]
[[41 39 37 ... 73 73 73]]
[[88 88 88 ... 76 75 74]]
[[59 59 59 ... 93 92 91]]
[[68 67 66 ... 87 87 87]]
[[74 81 87 ... 94 93 92]]
[[75 75 74 ... 99 99 99]]
[[89 89 89 ... 76 76 76]]
[[ 64  65  66 ... 102 101 100]]
[[41 40 37 ... 76 76 76]]
[[ 76  76  76 ... 104 104 104]]
[[100 100 101 ...  93  93  93]]
[[ 82  83  83 ... 103 103 103]]
[[ 95  97 100 ...  89  89  89]]
[[81 85 90 ... 94 94 94]]
[[113 113 114 ...  99  99  99]]
[[73 77 82 ... 86 86 86]]
[[94 94 94 ... 84 83 82]]
[[73 76 79 ... 91 91 91]]
[[ 99  99 100 ...  95  95  95]]
[[ 75  80  87 ... 102 102 102]]
[[66 69 73 ... 97 97 97]]
[[69 73 77 ... 95 95 95]]
[[89 90 92 ... 95 95 95]]
[[42 40 37 ... 78 78 78]]
[[ 68  73  81 ... 112 112 112]]
[[ 73  80  90 ... 110 110 110]]
[[ 70  71  71 ... 105 104 103]]
[[ 73  79  88 ... 105 105 105]]
[[71 76 78 ... 96 96 96]]
[[105 106 107 ...  97  97  97]]
[[ 69  71  71 ... 107 106 105]]
[[90 90 90 ... 82 82 82]]
[[ 70 

[[76 80 85 ... 86 86 86]]
[[53 53 54 ... 82 82 82]]
[[60 60 59 ... 91 91 91]]
[[60 60 61 ... 94 94 94]]
[[107 112 112 ... 106 106 106]]
[[39 38 38 ... 77 77 77]]
[[91 93 96 ... 97 97 97]]
[[106 108 110 ...  99  98  97]]
[[ 68  74  81 ... 115 115 115]]
[[ 71  76  83 ... 117 117 117]]
[[ 71  75  81 ... 113 113 113]]
[[91 92 94 ... 88 88 88]]
[[105 106 108 ...  97  97  97]]
[[85 89 94 ... 97 97 97]]
[[109 109 110 ... 104 104 104]]
[[ 66  67  68 ... 104 103 102]]
[[114 115 115 ... 108 108 108]]
[[95 96 97 ... 95 95 95]]
[[43 42 40 ... 77 77 77]]
[[39 38 36 ... 76 76 76]]
[[112 115 104 ... 103 103 103]]
[[ 66  74  84 ... 114 114 114]]
[[84 89 94 ... 96 96 96]]
[[ 71  77  87 ... 105 105 105]]
[[91 93 96 ... 97 97 97]]
[[ 68  74  81 ... 115 115 115]]
[[76 81 88 ... 93 92 91]]
[[103 103 104 ...  94  94  94]]
[[115 118 113 ... 109 109 109]]
[[ 71  78  88 ... 107 107 107]]
[[85 90 95 ... 97 97 97]]
[[74 74 73 ... 97 97 97]]
[[61 62 63 ... 96 95 94]]
[[ 64  64  65 ... 100 100 100]]
[[ 85  89  93 

[[110 110 111 ... 105 105 105]]
[[ 69  73  80 ... 113 113 113]]
[[ 68  75  85 ... 103 103 103]]
[[93 94 95 ... 87 87 87]]
[[98 98 99 ... 96 96 96]]
[[ 69  70  71 ... 109 108 107]]
[[ 68  69  70 ... 108 107 106]]
[[ 97  98  99 ... 103 103 103]]
[[78 82 87 ... 87 86 85]]
[[40 39 37 ... 79 79 79]]
[[ 66  67  68 ... 104 103 103]]
[[ 77  78  78 ... 104 104 104]]
[[41 40 38 ... 77 77 77]]
[[94 94 94 ... 84 83 83]]
[[59 60 62 ... 97 96 95]]
[[115 102 125 ... 107 107 107]]
[[ 70  75  84 ... 106 106 106]]
[[ 65  71  79 ... 112 112 112]]
[[79 82 87 ... 90 90 90]]
[[ 90  92  95 ... 102 102 102]]
[[ 66  74  84 ... 114 114 114]]
[[75 79 85 ... 86 85 85]]
[[69 74 76 ... 97 97 97]]
[[ 68  69  70 ... 106 105 104]]
[[45 43 40 ... 77 77 77]]
[[ 66  72  79 ... 111 111 111]]
[[ 69  72  78 ... 109 109 109]]
[[ 77  78  78 ... 104 104 104]]
[[ 69  75  83 ... 103 103 103]]
[[ 70  71  72 ... 109 108 108]]
[[ 70  74  80 ... 113 113 113]]
[[85 87 91 ... 97 97 97]]
[[ 72  78  86 ... 104 104 104]]
[[92 93 93 ... 8

[[ 92  96 101 ... 103 103 103]]
[[85 86 88 ... 78 78 78]]
[[ 85  89  94 ... 101 101 101]]
[[92 94 96 ... 84 84 84]]
[[ 83  83  83 ... 104 104 104]]
[[ 67  74  84 ... 103 103 103]]
[[ 67  68  68 ... 103 102 101]]
[[111 111 112 ...  98  98  98]]
[[ 87  90  94 ... 105 105 105]]
[[ 70  76  85 ... 103 103 103]]
[[40 39 37 ... 78 78 78]]
[[70 75 79 ... 96 96 96]]
[[59 59 60 ... 95 95 95]]
[[ 71  76  84 ... 116 116 116]]
[[94 94 94 ... 87 87 87]]
[[110 110 111 ...  94  94  94]]
[[ 86  89  94 ... 105 105 105]]
[[73 77 82 ... 86 86 86]]
[[104 104 105 ...  92  92  92]]
[[95 95 97 ... 95 95 95]]
[[96 96 96 ... 91 91 91]]
[[110 110 111 ...  96  96  96]]
[[ 67  67  66 ... 101 100  99]]
[[ 95  96  98 ... 103 103 103]]
[[42 41 38 ... 77 77 77]]
[[96 96 96 ... 98 98 98]]
[[ 64  65  67 ... 108 107 106]]
[[98 98 98 ... 86 85 84]]
[[71 76 78 ... 95 94 94]]
[[113 113 114 ... 106 106 106]]
[[74 76 75 ... 96 96 96]]
[[94 95 97 ... 95 95 95]]
[[110 110 111 ...  97  97  97]]
[[73 75 76 ... 95 95 95]]
[[39 38 

[[91 93 94 ... 82 82 82]]
[[95 95 95 ... 85 84 83]]
[[ 83  84  84 ... 105 105 105]]
[[90 90 90 ... 82 82 82]]
[[ 70  71  72 ... 113 112 111]]
[[91 92 92 ... 83 83 83]]
[[61 61 61 ... 97 96 95]]
[[98 98 99 ... 95 95 95]]
[[94 94 96 ... 99 98 98]]
[[67 70 74 ... 96 96 96]]
[[74 79 84 ... 85 84 83]]
[[103 104 106 ...  97  97  97]]
[[94 95 96 ... 97 97 97]]
[[ 70  71  72 ... 109 108 108]]
[[39 37 35 ... 77 77 77]]
[[64 65 66 ... 99 98 97]]
[[94 95 97 ... 99 99 99]]
[[62 63 64 ... 94 93 92]]
[[72 73 75 ... 95 95 95]]
[[110 110 111 ...  96  96  96]]
[[39 38 36 ... 76 76 76]]
[[106 107 108 ...  98  98  98]]
[[108 108 109 ...  94  94  94]]
[[ 94  97 102 ... 100 100 100]]
[[ 66  71  77 ... 104 104 104]]
[[ 85  88  93 ... 105 105 105]]
[[96 96 97 ... 98 98 98]]
[[ 97  99 101 ...  99  99  99]]
[[69 77 85 ... 86 86 86]]
[[42 40 39 ... 76 76 76]]
[[ 69  70  71 ... 109 109 108]]
[[ 67  68  69 ... 103 102 101]]
[[76 77 77 ... 97 97 97]]
[[90 90 91 ... 79 79 79]]
[[90 91 93 ... 95 95 95]]
[[ 95  98 10

[[84 88 94 ... 97 97 97]]
[[ 65  66  67 ... 105 104 103]]
[[78 78 78 ... 97 97 97]]
[[ 99  99 100 ...  88  88  88]]
[[90 91 92 ... 94 94 94]]
[[96 96 96 ... 89 89 89]]
[[86 89 92 ... 98 98 98]]
[[68 68 68 ... 95 95 95]]
[[110 110 111 ...  96  96  96]]
[[109 117 107 ... 104 104 104]]
[[121  99 102 ... 104 104 104]]
[[105 106 108 ...  94  94  94]]
[[87 87 87 ... 76 75 74]]
[[ 71  78  88 ... 106 106 106]]
[[91 93 94 ... 82 82 82]]
[[107 107 108 ...  94  94  94]]
[[ 95  98 101 ... 100 100 100]]
[[90 90 91 ... 90 90 90]]
[[97 97 97 ... 85 85 85]]
[[105 105 106 ... 100 100 100]]
[[90 91 93 ... 94 94 94]]
[[ 68  69  70 ... 101 100  99]]
[[ 84  84  84 ... 103 103 103]]
[[ 97  98 100 ...  93  93  93]]
[[ 66  67  68 ... 112 112 111]]
[[61 60 59 ... 82 82 82]]
[[59 62 67 ... 82 82 82]]
[[117  97 106 ... 107 106 106]]
[[100 100 101 ...  93  93  93]]
[[95 96 97 ... 88 88 88]]
[[77 81 85 ... 91 91 91]]
[[102 115 115 ... 104 104 104]]
[[ 69  69  70 ... 102 101 100]]
[[ 70  76  85 ... 107 107 107]]
[[

[[56 56 57 ... 84 84 84]]
[[121  99 102 ... 104 104 104]]
[[85 89 94 ... 97 97 97]]
[[ 70  76  83 ... 117 117 117]]
[[ 85  88  93 ... 105 105 105]]
[[68 70 73 ... 95 95 95]]
[[ 69  76  87 ... 110 110 110]]
[[94 94 94 ... 84 83 83]]
[[51 51 52 ... 78 78 78]]
[[83 84 86 ... 76 76 76]]
[[ 83  86  91 ... 103 103 103]]
[[88 88 88 ... 77 77 77]]
[[41 40 38 ... 77 77 77]]
[[ 67  68  69 ... 109 108 108]]
[[ 65  66  67 ... 102 101 101]]
[[ 68  73  80 ... 111 111 111]]
[[65 65 65 ... 95 95 95]]
[[73 80 87 ... 95 95 95]]
[[55 55 56 ... 85 85 85]]
[[ 70  76  85 ... 107 107 107]]
[[ 69  69  70 ... 102 101 100]]
[[102 115 115 ... 104 104 104]]
[[77 81 85 ... 91 91 91]]
[[92 92 92 ... 84 84 84]]
[[ 72  78  85 ... 120 120 120]]
[[88 90 94 ... 97 97 97]]
[[ 68  72  79 ... 114 114 114]]
[[58 58 59 ... 87 87 87]]
[[ 68  75  85 ... 108 108 108]]
[[73 75 77 ... 98 98 98]]
[[115 102 125 ... 107 107 107]]
[[77 81 87 ... 94 94 93]]
[[ 68  73  82 ... 112 112 112]]
[[73 73 72 ... 97 97 97]]
[[87 90 94 ... 98 98

[[96 96 96 ... 91 91 91]]
[[110 110 111 ...  96  96  96]]
[[ 67  67  66 ... 101 100  99]]
[[ 67  68  69 ... 107 106 105]]
[[ 95  96  98 ... 103 103 103]]
[[42 41 38 ... 77 77 77]]
[[ 64  65  67 ... 108 107 106]]
[[40 39 37 ... 78 78 78]]
[[70 75 79 ... 96 96 96]]
[[ 86  89  94 ... 105 105 105]]
[[94 94 94 ... 87 87 87]]
[[110 110 111 ...  94  94  94]]
[[59 59 60 ... 95 95 95]]
[[ 71  76  84 ... 116 116 116]]
[[73 77 82 ... 86 86 86]]
[[ 70  71  72 ... 110 109 108]]
[[104 104 105 ...  92  92  92]]
[[39 38 35 ... 73 73 73]]
[[ 69  70  71 ... 109 109 108]]
[[ 97  99 101 ...  99  99  99]]
[[42 40 39 ... 76 76 76]]
[[69 77 85 ... 86 86 86]]
[[ 66  71  77 ... 104 104 104]]
[[ 94  97 102 ... 100 100 100]]
[[96 96 97 ... 98 98 98]]
[[ 85  88  93 ... 105 105 105]]
[[108 108 109 ...  94  94  94]]
[[39 38 36 ... 76 76 76]]
[[106 107 108 ...  98  98  98]]
[[ 68  73  82 ... 114 114 114]]
[[72 73 75 ... 95 95 95]]
[[72 73 75 ... 95 95 95]]
[[62 63 64 ... 94 93 92]]
[[94 95 97 ... 99 99 99]]
[[39 37 

[[115 114 113 ... 110 110 110]]
[[ 69  69  70 ... 101 100  99]]
[[90 91 93 ... 95 95 95]]
[[79 84 90 ... 92 92 91]]
[[72 73 75 ... 95 95 95]]
[[72 73 75 ... 95 95 95]]
[[ 68  73  82 ... 114 114 114]]
[[106 107 108 ...  98  98  98]]
[[39 38 36 ... 76 76 76]]
[[108 108 109 ...  94  94  94]]
[[ 85  88  93 ... 105 105 105]]
[[96 96 97 ... 98 98 98]]
[[ 66  71  77 ... 104 104 104]]
[[ 94  97 102 ... 100 100 100]]
[[42 40 39 ... 76 76 76]]
[[69 77 85 ... 86 86 86]]
[[ 97  99 101 ...  99  99  99]]
[[ 69  70  71 ... 109 109 108]]
[[61 61 61 ... 97 96 95]]
[[94 94 96 ... 99 98 98]]
[[67 70 74 ... 96 96 96]]
[[80 85 90 ... 95 95 95]]
[[98 98 99 ... 95 95 95]]
[[103 104 106 ...  97  97  97]]
[[74 79 84 ... 85 84 83]]
[[79 83 88 ... 90 90 89]]
[[ 70  71  72 ... 109 108 108]]
[[ 67  68  69 ... 106 105 104]]
[[64 65 66 ... 99 98 97]]
[[39 37 35 ... 77 77 77]]
[[62 63 64 ... 94 93 92]]
[[94 95 97 ... 99 99 99]]
[[ 64  65  67 ... 108 107 106]]
[[42 41 38 ... 77 77 77]]
[[ 95  96  98 ... 103 103 103]]


[[ 68  69  70 ... 101 100  99]]
[[88 88 88 ... 82 82 82]]
[[121  99 102 ... 104 104 104]]
[[105 106 108 ...  94  94  94]]
[[87 87 87 ... 76 75 74]]
[[ 71  78  88 ... 106 106 106]]
[[ 99  99 100 ...  88  88  88]]
[[ 65  66  67 ... 105 104 103]]
[[90 91 92 ... 94 94 94]]
[[92 92 92 ... 83 83 83]]
[[88 91 96 ... 95 95 95]]
[[96 96 96 ... 89 89 89]]
[[ 71  77  86 ... 108 108 109]]
[[110 110 111 ...  96  96  96]]
[[68 68 68 ... 95 95 95]]
[[86 89 92 ... 98 98 98]]
[[73 75 77 ... 98 98 98]]
[[ 68  75  85 ... 108 108 108]]
[[58 58 59 ... 87 87 87]]
[[88 90 94 ... 97 97 97]]
[[ 68  72  79 ... 114 114 114]]
[[ 72  78  85 ... 120 120 120]]
[[92 92 92 ... 84 84 84]]
[[ 68  69  70 ... 108 108 107]]
[[105 106 108 ...  97  97  97]]
[[84 84 85 ... 76 76 76]]
[[ 83  86  90 ... 101 101 101]]
[[ 65  72  82 ... 103 103 103]]
[[67 70 74 ... 97 97 97]]
[[87 90 94 ... 98 98 98]]
[[73 73 72 ... 97 97 97]]
[[ 68  73  82 ... 112 112 112]]
[[77 81 87 ... 94 94 93]]
[[115 102 125 ... 107 107 107]]
[[51 51 52 ...

[[ 69  75  83 ... 103 103 103]]
[[109 109 110 ...  96  96  96]]
[[ 72  78  86 ... 104 104 104]]
[[96 96 96 ... 83 83 83]]
[[ 70  74  80 ... 113 113 113]]
[[40 39 38 ... 76 76 76]]
[[85 87 91 ... 97 97 97]]
[[39 38 37 ... 76 76 76]]
[[90 91 93 ... 93 93 93]]
[[ 69  73  80 ... 113 113 113]]
[[ 68  75  85 ... 103 103 103]]
[[ 69  70  71 ... 109 108 107]]
[[40 39 37 ... 79 79 79]]
[[91 91 91 ... 80 80 79]]
[[ 97  98  99 ... 103 103 103]]
[[85 85 85 ... 76 75 74]]
[[90 91 93 ... 94 94 94]]
[[41 40 38 ... 77 77 77]]
[[115 102 125 ... 107 107 107]]
[[ 65  71  79 ... 112 112 112]]
[[ 90  92  95 ... 102 102 102]]
[[108 108 109 ...  96  96  96]]
[[ 70  75  84 ... 106 106 106]]
[[104 105 106 ...  98  98  98]]
[[84 85 87 ... 89 89 89]]
[[105 106 108 ...  94  94  94]]
[[107 108 108 ... 100 100 100]]
[[112 110 100 ... 105 105 105]]
[[105 105 106 ...  96  96  96]]
[[91 93 96 ... 95 95 95]]
[[70 70 70 ... 97 97 97]]
[[75 79 85 ... 88 88 88]]
[[ 70  76  85 ... 107 107 107]]
[[95 96 97 ... 89 89 89]]
[[

[[ 62  64  65 ... 100  99  98]]
[[72 79 87 ... 91 91 91]]
[[ 81  82  82 ... 101 101 101]]
[[77 81 87 ... 94 94 93]]
[[74 76 79 ... 88 88 88]]
[[ 62  64  67 ... 104 103 102]]
[[ 71  77  85 ... 104 104 104]]
[[75 80 88 ... 93 93 93]]
[[91 94 97 ... 95 95 95]]
[[96 96 97 ... 99 98 97]]
[[ 67  68  69 ... 107 106 105]]
[[ 98  99 101 ...  94  94  94]]
[[ 70  77  86 ... 103 103 103]]
[[ 86  89  94 ... 105 105 105]]
[[ 68  69  71 ... 111 110 109]]
[[93 93 94 ... 95 95 95]]
[[ 72  76  81 ... 114 114 114]]
[[112 115 108 ... 104 103 102]]
[[ 69  71  71 ... 109 108 107]]
[[103 103 104 ...  94  94  94]]
[[39 38 36 ... 75 75 75]]
[[66 68 73 ... 97 97 97]]
[[ 86  89  94 ... 105 105 105]]
[[ 68  69  70 ... 110 109 108]]
[[ 85  88  93 ... 105 105 105]]
[[92 92 93 ... 94 94 94]]
[[87 90 92 ... 82 81 80]]
[[ 66  67  68 ... 102 101 100]]
[[112 112 113 ... 106 106 106]]
[[60 60 61 ... 94 94 94]]
[[ 84  84  84 ... 104 104 104]]
[[ 68  72  79 ... 110 110 110]]
[[65 66 67 ... 99 98 97]]
[[ 95  98 101 ...  98 

[[87 90 92 ... 82 81 80]]
[[92 92 93 ... 94 94 94]]
[[74 76 79 ... 88 88 88]]
[[77 81 87 ... 94 94 93]]
[[72 79 87 ... 91 91 91]]
[[ 81  82  82 ... 101 101 101]]
[[ 62  64  65 ... 100  99  98]]
[[ 66  67  68 ... 101 100  99]]
[[ 82  83  83 ... 103 103 103]]
[[96 97 98 ... 91 91 91]]
[[90 92 94 ... 84 84 84]]
[[79 83 89 ... 93 93 93]]
[[ 86  89  94 ... 105 105 105]]
[[ 98  99 101 ...  94  94  94]]
[[ 70  77  86 ... 103 103 103]]
[[ 67  68  69 ... 107 106 105]]
[[96 96 97 ... 99 98 97]]
[[91 94 97 ... 95 95 95]]
[[ 71  77  85 ... 104 104 104]]
[[75 80 88 ... 93 93 93]]
[[ 62  64  67 ... 104 103 102]]
[[ 83  83  83 ... 104 104 104]]
[[ 70  74  80 ... 116 116 116]]
[[85 86 88 ... 78 78 78]]
[[ 85  89  94 ... 101 101 101]]
[[92 94 96 ... 84 84 84]]
[[79 83 89 ... 94 94 94]]
[[ 66  67  68 ... 102 101 100]]
[[53 55 56 ... 85 84 83]]
[[76 83 88 ... 93 92 91]]
[[ 80  81  81 ... 100 100 100]]
[[ 70  76  85 ... 103 103 103]]
[[76 76 76 ... 97 97 97]]
[[ 70  75  84 ... 115 115 115]]
[[111 111 112 

[[ 90  92  95 ... 102 102 102]]
[[115 102 125 ... 107 107 107]]
[[41 40 38 ... 77 77 77]]
[[90 91 93 ... 94 94 94]]
[[85 85 85 ... 76 75 74]]
[[ 69  75  83 ... 103 103 103]]
[[ 67  69  71 ... 112 111 110]]
[[ 69  72  78 ... 109 109 109]]
[[45 43 40 ... 77 77 77]]
[[91 91 91 ... 80 79 78]]
[[ 68  69  70 ... 106 105 104]]
[[90 91 93 ... 93 93 93]]
[[39 38 37 ... 76 76 76]]
[[40 39 38 ... 76 76 76]]
[[ 70  74  80 ... 113 113 113]]
[[85 87 91 ... 97 97 97]]
[[ 72  78  86 ... 104 104 104]]
[[96 96 96 ... 83 83 83]]
[[109 109 110 ...  96  96  96]]
[[ 68  69  70 ... 108 108 107]]
[[106 106 107 ...  96  96  96]]
[[95 95 95 ... 83 83 83]]
[[ 83  86  90 ... 101 101 101]]
[[87 90 94 ... 98 98 98]]
[[58 59 60 ... 96 95 95]]
[[ 67  68  69 ... 105 104 103]]
[[73 73 72 ... 97 97 97]]
[[ 68  73  82 ... 112 112 112]]
[[ 68  75  85 ... 108 108 108]]
[[ 78  78  78 ... 102 102 102]]
[[73 75 77 ... 98 98 98]]
[[ 68  72  79 ... 114 114 114]]
[[76 81 87 ... 94 93 93]]
[[88 90 94 ... 97 97 97]]
[[58 58 59 ...

[[88 88 89 ... 77 77 77]]
[[ 67  72  80 ... 112 112 112]]
[[83 85 88 ... 87 87 87]]
[[41 40 39 ... 76 76 76]]
[[ 70  74  81 ... 114 114 114]]
[[104 105 106 ...  98  98  98]]
[[107 108 108 ... 100 100 100]]
[[105 106 108 ...  94  94  94]]
[[105 105 106 ...  96  96  96]]
[[91 93 96 ... 95 95 95]]
[[44 42 39 ... 78 78 78]]
[[70 70 70 ... 97 97 97]]
[[95 96 97 ... 89 89 89]]
[[97 97 97 ... 89 89 89]]
[[75 79 85 ... 88 88 88]]
[[ 70  76  85 ... 107 107 107]]
[[ 87  91  97 ... 101 101 101]]
[[97 97 98 ... 90 90 90]]
[[ 67  69  71 ... 109 108 108]]
[[61 60 59 ... 82 82 82]]
[[ 73  79  88 ... 105 105 105]]
[[ 97  98 100 ...  93  93  93]]
[[ 64  65  67 ... 108 107 106]]
[[ 74  74  74 ... 102 102 102]]
[[90 90 91 ... 90 90 90]]
[[ 67  72  80 ... 112 112 112]]
[[ 68  69  70 ... 101 100  99]]
[[107 107 108 ...  94  94  94]]
[[70 72 75 ... 96 96 96]]
[[ 85  87  92 ... 100 100 100]]
[[ 69  70  71 ... 112 111 110]]
[[ 66  68  70 ... 109 109 108]]
[[105 106 108 ...  94  94  94]]
[[ 85  87  92 ... 100 

[[90 90 90 ... 80 79 78]]
[[67 73 78 ... 93 93 93]]
[[112 113 113 ... 108 108 108]]
[[ 66  67  68 ... 112 112 111]]
[[97 97 97 ... 87 87 87]]
[[41 40 39 ... 77 77 77]]
[[74 76 75 ... 96 96 96]]
[[91 92 94 ... 92 92 92]]
[[ 85  88  93 ... 104 104 104]]
[[ 67  72  79 ... 103 103 103]]
[[106 106 107 ...  93  93  93]]
[[90 91 93 ... 95 95 95]]
[[102 102 103 ...  97  97  97]]
[[77 78 78 ... 97 97 97]]
[[ 69  69  70 ... 101 100  99]]
[[74 78 84 ... 88 88 87]]
[[41 40 39 ... 76 76 76]]
[[ 95  98 102 ... 100 100 100]]
[[58 59 60 ... 92 91 91]]
[[109 118 105 ... 106 106 105]]
[[ 67  68  69 ... 103 102 101]]
[[42 40 39 ... 76 76 76]]
[[ 97  99 101 ...  99  99  99]]
[[ 77  77  77 ... 102 102 102]]
[[ 69  70  71 ... 109 109 108]]
[[96 96 97 ... 87 87 87]]
[[108 108 109 ...  94  94  94]]
[[ 85  88  93 ... 105 105 105]]
[[ 66  71  77 ... 104 104 104]]
[[89 89 90 ... 77 77 77]]
[[39 38 36 ... 76 76 76]]
[[89 90 92 ... 95 95 95]]
[[64 65 66 ... 99 98 97]]
[[113 109 105 ... 105 105 105]]
[[39 37 35 ...

[[ 72  78  85 ... 120 120 120]]
[[56 56 57 ... 87 87 87]]
[[39 38 36 ... 78 78 78]]
[[73 75 76 ... 95 95 95]]
[[79 84 90 ... 96 96 96]]
[[66 65 64 ... 84 84 84]]
[[110 110 111 ...  97  97  97]]
[[108 108 109 ...  96  96  96]]
[[71 76 78 ... 95 94 94]]
[[ 64  65  67 ... 108 107 106]]
[[72 73 73 ... 97 97 97]]
[[ 95  96  98 ... 103 103 103]]
[[97 97 97 ... 85 85 85]]
[[90 92 94 ... 84 84 84]]
[[41 40 39 ... 77 77 77]]
[[ 97  98 100 ... 103 103 103]]
[[96 96 96 ... 91 91 91]]
[[104 104 105 ...  92  92  92]]
[[104 104 105 ...  92  92  92]]
[[110 110 111 ...  94  94  94]]
[[94 94 94 ... 87 87 87]]
[[ 71  76  84 ... 116 116 116]]
[[70 75 79 ... 96 96 96]]
[[96 96 97 ... 84 84 84]]
[[40 39 37 ... 78 78 78]]
[[ 67  72  80 ... 112 112 112]]
[[93 94 95 ... 87 87 87]]
[[ 70  75  81 ... 110 110 110]]
[[64 66 67 ... 99 98 97]]
[[ 66  67  68 ... 101 100  99]]
[[93 93 94 ... 90 90 90]]
[[70 73 77 ... 97 97 97]]
[[92 92 92 ... 80 80 79]]
[[81 85 90 ... 92 92 92]]
[[75 75 74 ... 99 99 99]]
[[98 98 98 .

[[73 73 72 ... 97 97 97]]
[[ 67  68  69 ... 105 104 103]]
[[ 66  71  77 ... 104 104 104]]
[[ 64  71  81 ... 103 103 103]]
[[94 94 96 ... 99 98 98]]
[[ 78  78  78 ... 102 102 102]]
[[ 98  99 101 ...  93  93  93]]
[[ 78  79  79 ... 106 106 106]]
[[70 75 77 ... 95 95 95]]
[[95 95 96 ... 90 90 90]]
[[42 39 36 ... 78 78 78]]
[[39 38 36 ... 75 75 75]]
[[85 86 88 ... 79 79 79]]
[[58 58 59 ... 92 92 92]]
[[95 95 96 ... 90 90 90]]
[[87 87 87 ... 78 78 77]]
[[62 64 68 ... 91 91 91]]
[[111 111 112 ... 107 107 107]]
[[40 39 38 ... 76 76 76]]
[[76 83 90 ... 94 94 94]]
[[95 95 96 ... 87 86 86]]
[[70 71 71 ... 97 97 97]]
[[ 74  74  74 ... 102 102 102]]
[[95 96 97 ... 89 89 89]]
[[39 38 36 ... 76 76 76]]
[[73 79 86 ... 87 87 87]]
[[ 85  88  93 ... 105 105 105]]
[[58 58 59 ... 92 92 92]]
[[ 73  79  87 ... 106 106 106]]
[[71 71 71 ... 97 97 97]]
[[100 100 101 ...  95  95  95]]
[[71 72 73 ... 97 97 97]]
[[43 40 37 ... 78 77 77]]
[[85 87 91 ... 97 97 97]]
[[103 103 104 ...  94  94  94]]
[[68 68 67 ... 95 

[[93 95 98 ... 91 91 91]]
[[ 97  98 100 ... 103 103 103]]
[[ 93  96 100 ...  97  97  97]]
[[83 84 86 ... 76 76 76]]
[[ 68  77  88 ... 105 105 105]]
[[102 103 104 ...  96  96  96]]
[[78 81 84 ... 94 94 94]]
[[98 98 98 ... 87 86 86]]
[[104 114 109 ... 106 105 104]]
[[ 70  76  86 ... 109 109 109]]
[[ 66  67  68 ... 107 106 105]]
[[ 65  72  82 ... 103 103 103]]
[[ 67  72  80 ... 112 112 112]]
[[ 67  69  71 ... 112 111 110]]
[[110 110 111 ...  94  94  94]]
[[ 82  85  90 ... 102 102 102]]
[[91 91 91 ... 82 82 82]]
[[88 91 94 ... 99 99 99]]
[[ 82  83  83 ... 104 104 104]]
[[ 71  78  88 ... 109 109 109]]
[[67 70 75 ... 97 97 97]]
[[ 78  78  78 ... 104 104 104]]
[[88 91 94 ... 93 93 93]]
[[60 60 61 ... 94 94 94]]
[[ 68  73  80 ... 111 111 111]]
[[ 64  72  82 ... 111 111 111]]
[[84 88 94 ... 97 97 97]]
[[61 61 62 ... 94 94 94]]
[[ 67  69  71 ... 112 111 110]]
[[38 38 36 ... 76 76 76]]
[[84 85 87 ... 77 77 77]]
[[109 109 110 ... 104 104 104]]
[[82 85 89 ... 99 99 99]]
[[59 59 59 ... 93 92 91]]
[[

[[58 58 59 ... 92 92 92]]
[[79 83 88 ... 92 92 92]]
[[94 95 96 ... 83 83 83]]
[[104 105 106 ... 102 102 102]]
[[68 68 68 ... 95 95 95]]
[[81 84 88 ... 95 95 95]]
[[76 81 86 ... 91 91 91]]
[[ 99 100 102 ...  95  95  95]]
[[74 80 90 ... 95 94 94]]
[[95 96 97 ... 91 91 91]]
[[72 74 76 ... 97 97 97]]
[[78 82 88 ... 93 93 93]]
[[61 62 63 ... 96 95 94]]
[[99 98 97 ... 91 91 91]]
[[73 77 82 ... 83 83 83]]
[[88 88 88 ... 77 76 75]]
[[111 111 112 ...  98  98  98]]
[[ 66  72  80 ... 113 113 113]]
[[63 63 64 ... 97 97 97]]
[[ 99 100 102 ...  93  93  93]]
[[ 69  75  84 ... 106 106 106]]
[[88 88 89 ... 76 76 76]]
[[62 62 63 ... 82 82 82]]
[[ 66  67  69 ... 102 101 100]]
[[ 82  83  83 ... 103 103 103]]
[[98 98 98 ... 86 85 84]]
[[41 40 39 ... 77 77 77]]
[[95 96 97 ... 91 91 91]]
[[92 93 94 ... 84 84 84]]
[[ 70  75  83 ... 116 116 116]]
[[39 38 35 ... 75 75 75]]
[[100 100 101 ...  93  93  93]]
[[70 75 76 ... 95 95 95]]
[[69 74 78 ... 97 97 97]]
[[113 113 114 ... 108 108 108]]
[[94 95 97 ... 99 99 99]

[[91 94 97 ... 95 95 95]]
[[65 65 64 ... 99 98 97]]
[[50 50 51 ... 73 73 73]]
[[ 80  80  81 ... 102 102 102]]
[[96 96 96 ... 85 85 85]]
[[94 94 93 ... 83 83 83]]
[[70 73 76 ... 95 95 95]]
[[ 67  72  80 ... 111 111 111]]
[[75 79 85 ... 88 88 88]]
[[102 103 104 ...  94  94  94]]
[[ 85  88  93 ... 106 106 106]]
[[ 66  71  79 ... 111 111 111]]
[[ 99  99 100 ...  95  95  95]]
[[98 98 98 ... 86 85 85]]
[[67 68 68 ... 97 96 96]]
[[69 72 76 ... 94 94 94]]
[[ 67  73  82 ... 102 101 100]]
[[62 62 61 ... 98 97 96]]
[[ 72  77  85 ... 104 104 104]]
[[96 96 96 ... 86 85 84]]
[[90 90 90 ... 83 82 82]]
[[ 71  76  84 ... 116 116 116]]
[[90 90 90 ... 82 82 82]]
[[63 63 64 ... 94 94 94]]
[[78 82 87 ... 92 91 91]]
[[64 67 71 ... 96 96 96]]
[[64 67 71 ... 94 94 94]]
[[ 69  75  83 ... 104 104 104]]
[[ 95  96  98 ... 100 100 100]]
[[93 94 95 ... 83 83 83]]
[[ 65  66  67 ... 104 103 102]]
[[ 68  68  68 ... 101 100  99]]
[[87 87 88 ... 92 92 92]]
[[ 82  83  83 ... 103 103 103]]
[[106 106 107 ...  95  95  95]]


[[103 103 104 ...  97  97  97]]
[[71 71 71 ... 99 99 99]]
[[94 94 94 ... 84 83 82]]
[[ 66  71  79 ... 111 111 111]]
[[109 111 113 ... 105 105 105]]
[[ 82  86  91 ... 103 103 103]]
[[69 72 76 ... 97 97 97]]
[[117 104 115 ... 109 109 109]]
[[61 61 62 ... 94 93 92]]
[[55 55 56 ... 84 84 84]]
[[80 84 89 ... 89 89 89]]
[[100 101 103 ...  95  95  95]]
[[72 72 72 ... 98 98 98]]
[[53 54 55 ... 74 74 74]]
[[111 112 112 ... 104 104 104]]
[[58 58 59 ... 87 87 87]]
[[81 81 82 ... 75 75 75]]
[[94 95 96 ... 95 95 95]]
[[67 68 69 ... 97 97 96]]
[[91 92 94 ... 84 84 84]]
[[95 96 97 ... 95 95 95]]
[[90 93 96 ... 89 89 89]]
[[94 94 95 ... 81 81 81]]
[[98 98 98 ... 86 85 84]]
[[ 74  74  74 ... 101 101 101]]
[[92 93 95 ... 89 89 89]]
[[91 94 98 ... 95 95 95]]
[[ 77  77  77 ... 102 102 102]]
[[87 87 87 ... 75 74 73]]
[[95 95 96 ... 91 91 91]]
[[93 93 93 ... 81 81 81]]
[[69 69 70 ... 97 97 97]]
[[109 109 110 ... 104 104 104]]
[[38 38 38 ... 78 78 78]]
[[95 96 98 ... 96 95 94]]
[[109 109 109 ... 103 103 103]

[[ 99 100 101 ...  90  90  90]]
[[58 58 59 ... 91 91 91]]
[[ 67  72  81 ... 115 115 115]]
[[ 70  74  80 ... 116 116 116]]
[[105 105 106 ...  99  99  99]]
[[106 108 110 ...  99  98  97]]
[[ 78  78  78 ... 104 104 104]]
[[75 73 71 ... 95 95 95]]
[[42 41 39 ... 77 77 77]]
[[57 59 60 ... 92 91 90]]
[[98 98 99 ... 91 91 91]]
[[73 78 85 ... 92 92 92]]
[[ 93  96 100 ...  97  97  97]]
[[ 97  98 100 ... 103 103 103]]
[[102 103 104 ...  96  96  96]]
[[ 68  77  88 ... 105 105 105]]
[[83 84 86 ... 76 76 76]]
[[79 83 88 ... 87 87 87]]
[[86 87 89 ... 78 78 78]]
[[72 73 76 ... 98 98 98]]
[[57 59 60 ... 92 91 90]]
[[81 83 87 ... 95 95 95]]
[[96 96 97 ... 90 90 90]]
[[59 59 60 ... 95 95 95]]
[[60 64 69 ... 91 91 91]]
[[ 64  65  66 ... 101  99  98]]
[[77 81 86 ... 95 95 95]]
[[109 109 110 ... 102 102 102]]
[[74 76 79 ... 88 88 88]]
[[ 99 100 101 ...  95  95  95]]
[[ 70  79  89 ... 106 106 106]]
[[ 73  73  73 ... 102 102 102]]
[[66 65 64 ... 92 92 92]]
[[ 80  80  80 ... 103 103 103]]
[[41 40 38 ... 79 79

[[68 68 68 ... 95 95 95]]
[[95 96 97 ... 89 89 89]]
[[67 67 67 ... 97 97 97]]
[[64 67 71 ... 94 94 94]]
[[107 107 108 ... 101 100  99]]
[[70 75 77 ... 91 91 91]]
[[75 79 85 ... 86 85 85]]
[[68 68 68 ... 95 95 95]]
[[98 98 98 ... 87 86 85]]
[[89 89 89 ... 76 76 76]]
[[40 39 38 ... 76 76 76]]
[[86 87 89 ... 78 78 78]]
[[104 104 105 ...  98  98  98]]
[[77 81 87 ... 91 91 91]]
[[95 95 96 ... 89 89 89]]
[[94 94 94 ... 81 80 79]]
[[75 80 88 ... 93 93 93]]
[[95 95 95 ... 88 88 88]]
[[78 81 86 ... 91 91 91]]
[[96 97 98 ... 90 90 90]]
[[72 77 81 ... 98 98 98]]
[[82 85 90 ... 90 90 90]]
[[112 112 113 ... 100 100 100]]
[[ 69  70  71 ... 110 109 108]]
[[ 66  68  70 ... 112 111 111]]
[[98 98 99 ... 91 91 90]]
[[70 70 70 ... 99 99 99]]
[[78 82 88 ... 93 93 93]]
[[121 102 108 ... 108 107 106]]
[[61 62 63 ... 96 95 94]]
[[99 98 97 ... 91 91 91]]
[[111 111 112 ...  98  98  98]]
[[73 77 82 ... 83 83 83]]
[[88 88 88 ... 77 76 75]]
[[63 63 64 ... 97 97 97]]
[[ 66  72  80 ... 113 113 113]]
[[ 69  75  84 ..

[[80 84 90 ... 93 93 93]]
[[103 104 105 ...  98  98  98]]
[[ 72  73  73 ... 101 101 101]]
[[ 67  68  69 ... 107 106 105]]
[[ 66  67  68 ... 103 102 102]]
[[98 98 98 ... 89 89 89]]
[[ 99 100 102 ...  94  94  94]]
[[65 66 67 ... 99 98 97]]
[[96 96 97 ... 99 98 97]]
[[93 93 94 ... 83 83 82]]
[[105 107 108 ... 101 101 101]]
[[104 104 105 ...  94  94  94]]
[[ 69  70  71 ... 107 106 105]]
[[78 81 87 ... 90 90 89]]
[[97 97 97 ... 89 89 89]]
[[40 38 36 ... 75 75 75]]
[[ 70  70  69 ... 103 102 101]]
[[71 71 71 ... 98 98 98]]
[[ 63  64  66 ... 102 101 100]]
[[85 85 85 ... 72 71 71]]
[[88 88 89 ... 92 92 92]]
[[ 70  74  81 ... 114 114 114]]
[[82 85 90 ... 90 90 90]]
[[96 96 96 ... 90 90 90]]
[[96 96 97 ... 94 94 94]]
[[ 66  71  79 ... 111 111 111]]
[[ 71  76  84 ... 116 116 116]]
[[111 111 112 ... 103 103 103]]
[[90 90 90 ... 83 82 82]]
[[90 90 90 ... 82 82 82]]
[[63 63 64 ... 94 94 94]]
[[108 108 109 ...  99  99  99]]
[[64 67 71 ... 96 96 96]]
[[64 67 71 ... 94 94 94]]
[[70 73 76 ... 95 95 95]]


[[111 112 113 ... 106 106 106]]
[[53 54 54 ... 79 79 79]]
[[79 83 88 ... 87 87 87]]
[[ 98  99 100 ...  95  95  95]]
[[66 65 64 ... 84 84 84]]
[[ 64  65  66 ... 102 101 100]]
[[60 61 62 ... 96 95 94]]
[[ 73  73  73 ... 101 101 101]]
[[95 96 97 ... 89 89 89]]
[[67 66 65 ... 87 87 87]]
[[107 107 108 ... 101 101 101]]
[[ 69  74  81 ... 113 113 113]]
[[ 67  72  81 ... 113 113 113]]
[[66 66 66 ... 97 97 97]]
[[80 84 89 ... 89 89 89]]
[[100 101 103 ...  95  95  95]]
[[72 72 72 ... 98 98 98]]
[[53 54 55 ... 74 74 74]]
[[81 81 82 ... 75 75 75]]
[[111 112 112 ... 104 104 104]]
[[58 58 59 ... 87 87 87]]
[[94 95 96 ... 95 95 95]]
[[67 68 69 ... 97 97 96]]
[[94 94 94 ... 84 83 82]]
[[109 111 113 ... 105 105 105]]
[[ 82  86  91 ... 103 103 103]]
[[95 95 96 ... 86 85 85]]
[[61 61 62 ... 94 93 92]]
[[69 72 76 ... 97 97 97]]
[[68 73 80 ... 99 99 99]]
[[55 55 56 ... 84 84 84]]
[[86 87 89 ... 83 83 83]]
[[68 67 66 ... 87 87 87]]
[[ 99 100 101 ...  94  94  94]]
[[93 94 96 ... 87 87 87]]
[[79 84 89 ... 89 

[[68 68 67 ... 95 95 95]]
[[66 67 70 ... 92 92 91]]
[[91 91 91 ... 80 79 78]]
[[95 95 95 ... 89 89 89]]
[[111 111 112 ... 107 107 107]]
[[109 111 115 ... 109 109 109]]
[[103 103 104 ...  98  98  98]]
[[42 40 39 ... 76 76 76]]
[[98 98 98 ... 87 86 86]]
[[100 100 100 ...  89  89  89]]
[[101 101 102 ...  97  97  97]]
[[95 95 96 ... 86 86 85]]
[[ 66  67  68 ... 106 105 104]]
[[111 111 112 ... 107 107 107]]
[[81 83 87 ... 95 95 95]]
[[96 96 97 ... 90 90 90]]
[[59 59 60 ... 95 95 95]]
[[77 81 86 ... 95 95 95]]
[[109 109 110 ... 102 102 102]]
[[ 80  81  81 ... 101 101 101]]
[[ 64  65  66 ... 101  99  98]]
[[60 64 69 ... 91 91 91]]
[[ 78  78  78 ... 104 104 104]]
[[67 66 65 ... 87 87 87]]
[[42 41 39 ... 77 77 77]]
[[98 98 99 ... 91 91 91]]
[[83 85 88 ... 87 87 87]]
[[57 59 60 ... 92 91 90]]
[[71 71 71 ... 95 95 95]]
[[63 63 64 ... 97 97 97]]
[[ 80  81  81 ... 107 107 107]]
[[ 88  91  95 ... 105 105 105]]
[[102 103 104 ...  96  96  96]]
[[ 68  77  88 ... 105 105 105]]
[[96 96 96 ... 89 89 89]]


[[91 92 94 ... 84 84 84]]
[[ 84  87  92 ... 105 105 105]]
[[ 69  73  79 ... 112 112 112]]
[[61 61 62 ... 95 95 95]]
[[95 95 96 ... 89 89 89]]
[[94 94 93 ... 83 83 83]]
[[65 65 64 ... 99 98 97]]
[[ 68  73  82 ... 114 114 114]]
[[ 80  80  81 ... 102 102 102]]
[[67 71 76 ... 98 98 98]]
[[97 97 97 ... 86 86 86]]
[[63 66 71 ... 95 95 95]]
[[91 94 97 ... 95 95 95]]
[[63 63 63 ... 95 95 95]]
[[67 68 68 ... 97 96 96]]
[[69 72 76 ... 94 94 94]]
[[103 103 104 ...  94  94  94]]
[[62 62 61 ... 98 97 96]]
[[ 85  88  93 ... 106 106 106]]
[[ 66  71  79 ... 111 111 111]]
[[ 66  67  68 ... 104 103 102]]
[[94 94 94 ... 90 90 90]]
[[62 62 61 ... 98 97 96]]
[[ 67  72  80 ... 111 111 111]]
[[64 67 71 ... 96 96 96]]
[[76 81 87 ... 96 95 95]]
[[64 67 71 ... 94 94 94]]
[[63 63 64 ... 94 94 94]]
[[71 71 71 ... 97 97 97]]
[[90 90 90 ... 83 82 82]]
[[94 95 96 ... 83 83 83]]
[[104 105 106 ... 102 102 102]]
[[91 91 91 ... 82 82 82]]
[[ 99 100 102 ...  95  95  95]]
[[74 80 90 ... 95 94 94]]
[[76 81 86 ... 91 91 91]

[[ 99 100 102 ...  93  93  93]]
[[73 77 82 ... 83 83 83]]
[[ 66  72  80 ... 113 113 113]]
[[ 63  64  66 ... 102 101 100]]
[[63 63 64 ... 97 97 97]]
[[94 94 95 ... 90 90 90]]
[[78 82 88 ... 93 93 93]]
[[99 98 97 ... 91 91 91]]
[[61 62 63 ... 96 95 94]]
[[ 67  72  80 ... 111 111 111]]
[[62 62 61 ... 98 97 96]]
[[94 94 94 ... 90 90 90]]
[[ 66  67  68 ... 104 103 102]]
[[ 85  88  93 ... 106 106 106]]
[[ 66  71  79 ... 111 111 111]]
[[62 62 61 ... 98 97 96]]
[[69 72 76 ... 94 94 94]]
[[103 103 104 ...  94  94  94]]
[[67 68 68 ... 97 96 96]]
[[90 90 90 ... 83 82 82]]
[[71 71 71 ... 97 97 97]]
[[63 63 64 ... 94 94 94]]
[[76 81 87 ... 96 95 95]]
[[64 67 71 ... 94 94 94]]
[[64 67 71 ... 96 96 96]]
[[95 95 96 ... 89 89 89]]
[[ 84  87  92 ... 105 105 105]]
[[91 92 94 ... 84 84 84]]
[[61 61 62 ... 95 95 95]]
[[ 69  73  79 ... 112 112 112]]
[[66 69 73 ... 95 95 95]]
[[ 69  70  71 ... 110 109 108]]
[[58 59 60 ... 96 95 95]]
[[113 116 105 ... 109 109 109]]
[[91 91 92 ... 93 93 93]]
[[40 39 36 ... 75 

[[60 64 69 ... 91 91 91]]
[[ 80  81  81 ... 101 101 101]]
[[109 109 110 ... 102 102 102]]
[[77 81 86 ... 95 95 95]]
[[59 59 60 ... 95 95 95]]
[[96 96 97 ... 90 90 90]]
[[81 83 87 ... 95 95 95]]
[[111 111 112 ... 107 107 107]]
[[ 66  67  68 ... 106 105 104]]
[[95 95 96 ... 86 86 85]]
[[101 101 102 ...  97  97  97]]
[[ 68  77  88 ... 105 105 105]]
[[102 103 104 ...  96  96  96]]
[[ 88  91  95 ... 105 105 105]]
[[ 80  81  81 ... 107 107 107]]
[[63 63 64 ... 97 97 97]]
[[71 71 71 ... 95 95 95]]
[[83 85 88 ... 87 87 87]]
[[98 98 99 ... 91 91 91]]
[[57 59 60 ... 92 91 90]]
[[42 41 39 ... 77 77 77]]
[[67 66 65 ... 87 87 87]]
[[ 78  78  78 ... 104 104 104]]
[[95 95 96 ... 88 88 88]]
[[ 99 100 101 ...  98  98  98]]
[[ 85  84  83 ... 110 110 110]]
[[ 80  81  81 ... 107 107 107]]
[[ 95  98 102 ... 100 100 100]]
[[44 42 40 ... 83 83 83]]
[[ 66  73  82 ... 113 112 111]]
[[92 92 93 ... 94 94 94]]
[[95 95 95 ... 84 84 84]]
[[94 94 95 ... 90 90 90]]
[[94 95 95 ... 93 93 93]]
[[95 95 96 ... 91 91 91]]


[[ 67  68  69 ... 106 105 104]]
[[109 109 110 ... 105 105 105]]
[[ 99  99 100 ...  92  92  92]]
[[97 97 97 ... 87 87 87]]
[[90 90 90 ... 79 78 77]]
[[73 74 74 ... 96 96 96]]
[[109 109 110 ... 104 104 104]]
[[95 96 98 ... 96 95 94]]
[[93 93 93 ... 81 81 81]]
[[90 90 90 ... 78 78 78]]
[[79 84 90 ... 96 96 96]]
[[69 69 70 ... 97 97 97]]
[[ 77  77  77 ... 102 102 102]]
[[85 86 87 ... 93 93 93]]
[[56 56 57 ... 84 84 84]]
[[92 93 95 ... 89 89 89]]
[[97 97 98 ... 97 96 96]]
[[ 74  74  74 ... 101 101 101]]
[[ 72  79  88 ... 106 106 106]]
[[63 64 64 ... 84 84 84]]
[[95 96 97 ... 95 95 95]]
[[91 92 94 ... 84 84 84]]
[[81 84 90 ... 95 95 95]]
[[90 93 96 ... 89 89 89]]
[[109 109 109 ... 103 103 103]]
[[ 70  79  89 ... 106 106 106]]
[[ 99 100 101 ...  95  95  95]]
[[ 80  80  80 ... 103 103 103]]
[[61 61 61 ... 97 96 95]]
[[68 74 78 ... 91 91 91]]
[[102 105 109 ... 100 100 100]]
[[41 40 38 ... 79 79 79]]
[[60 61 61 ... 90 90 90]]
[[40 39 37 ... 77 77 77]]
[[96 96 96 ... 89 89 89]]
[[88 88 88 ... 77 

[[97 97 97 ... 89 89 89]]
[[94 95 96 ... 83 83 83]]
[[65 70 77 ... 99 99 99]]
[[41 39 37 ... 76 76 76]]
[[96 96 97 ... 94 94 94]]
[[ 67  69  71 ... 112 111 110]]
[[ 63  64  66 ... 102 101 100]]
[[88 88 89 ... 92 92 92]]
[[96 96 96 ... 90 90 90]]
[[71 71 71 ... 98 98 98]]
[[64 67 71 ... 96 96 96]]
[[64 67 71 ... 94 94 94]]
[[76 81 87 ... 96 95 95]]
[[63 63 64 ... 94 94 94]]
[[71 71 71 ... 97 97 97]]
[[90 90 90 ... 83 82 82]]
[[103 103 104 ...  94  94  94]]
[[69 72 76 ... 94 94 94]]
[[67 68 68 ... 97 96 96]]
[[62 62 61 ... 98 97 96]]
[[ 66  71  79 ... 111 111 111]]
[[ 85  88  93 ... 106 106 106]]
[[ 66  67  68 ... 104 103 102]]
[[75 80 85 ... 87 87 87]]
[[ 67  72  80 ... 111 111 111]]
[[62 62 61 ... 98 97 96]]
[[94 94 93 ... 83 83 83]]
[[ 68  73  82 ... 114 114 114]]
[[65 65 64 ... 99 98 97]]
[[ 80  80  81 ... 102 102 102]]
[[67 71 76 ... 98 98 98]]
[[91 94 97 ... 95 95 95]]
[[97 97 97 ... 86 86 86]]
[[63 66 71 ... 95 95 95]]
[[63 63 63 ... 95 95 95]]
[[78 82 88 ... 87 87 87]]
[[ 65  70 

[[99 98 97 ... 91 91 91]]
[[61 62 63 ... 96 95 94]]
[[76 81 86 ... 91 91 91]]
[[74 80 90 ... 95 94 94]]
[[ 99 100 102 ...  95  95  95]]
[[104 105 106 ... 102 102 102]]
[[ 83  84  84 ... 105 105 105]]
[[94 95 96 ... 83 83 83]]
[[92 93 94 ... 84 84 84]]
[[58 58 59 ... 92 92 92]]
[[ 72  76  81 ... 114 114 114]]
[[79 83 88 ... 92 92 92]]
[[95 97 99 ... 89 89 89]]
[[ 68  69  70 ... 109 108 108]]
[[90 91 93 ... 84 84 84]]
[[76 80 86 ... 89 89 89]]
[[ 67  72  80 ... 114 114 114]]
[[96 96 96 ... 83 83 83]]
[[ 81  82  82 ... 104 104 104]]
[[ 78  79  79 ... 106 106 106]]
[[ 87  91  97 ... 101 101 101]]
[[94 94 96 ... 88 88 88]]
[[78 82 88 ... 89 89 89]]
[[63 63 63 ... 95 95 95]]
[[63 66 71 ... 95 95 95]]
[[97 97 97 ... 86 86 86]]
[[91 94 97 ... 95 95 95]]
[[67 71 76 ... 98 98 98]]
[[ 80  80  81 ... 102 102 102]]
[[ 68  73  82 ... 114 114 114]]
[[65 65 64 ... 99 98 97]]
[[94 94 93 ... 83 83 83]]
[[61 61 62 ... 95 95 95]]
[[ 69  73  79 ... 112 112 112]]
[[ 84  87  92 ... 105 105 105]]
[[95 95 96 .

[[41 40 38 ... 77 77 77]]
[[ 99 100 101 ...  90  90  90]]
[[89 90 92 ... 83 83 83]]
[[63 64 64 ... 84 84 84]]
[[92 93 95 ... 96 96 96]]
[[102 103 104 ...  96  96  96]]
[[ 68  77  88 ... 105 105 105]]
[[63 63 64 ... 97 97 97]]
[[ 88  91  95 ... 105 105 105]]
[[ 80  81  81 ... 107 107 107]]
[[100 100 101 ...  93  93  93]]
[[42 41 39 ... 77 77 77]]
[[57 59 60 ... 92 91 90]]
[[98 98 99 ... 91 91 91]]
[[83 85 88 ... 87 87 87]]
[[67 66 65 ... 87 87 87]]
[[ 96  98 101 ...  89  89  89]]
[[ 78  78  78 ... 104 104 104]]
[[60 64 69 ... 91 91 91]]
[[ 64  65  66 ... 101  99  98]]
[[77 81 86 ... 95 95 95]]
[[ 80  81  81 ... 101 101 101]]
[[109 109 110 ... 102 102 102]]
[[96 96 97 ... 90 90 90]]
[[59 59 60 ... 95 95 95]]
[[95 95 95 ... 88 88 88]]
[[111 111 112 ... 107 107 107]]
[[111 111 112 ... 107 107 107]]
[[ 66  67  68 ... 106 105 104]]
[[81 83 87 ... 95 95 95]]
[[96 96 96 ... 84 83 82]]
[[102 105 109 ... 100 100 100]]
[[41 40 38 ... 79 79 79]]
[[61 61 61 ... 97 96 95]]
[[68 74 78 ... 91 91 91]]


In [ ]:
import numpy as np
import os

IMG_DIR = '/Users/ozgecanyuzer/Documents/Classes/Ling_412/Preprocessing/Cropped Images/train'

for img in os.listdir(IMG_DIR):
        img_array = cv2.imread(os.path.join(IMG_DIR,img), cv2.IMREAD_GRAYSCALE)
        if img_array is not None:
            img_array = (img_array.flatten())
            img_array  = img_array.reshape(-1, 1).T
            print(img_array)
            save('data_3.npy', img_array)
            
        